linters:
  enable:
    - bodyclose
    - errorlint
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - godot
    - gosec
    - makezero
    - misspell
    - nakedret
    - nestif
    - noctx
    - predeclared
    - unconvert
    - whitespace
linters-settings:
  gosec:
    excludes:
      - G204
  gocognit:
    min-complexity: 40
  nestif:
    min-complexity: 40
  exhaustive:
    default-signifies-exhaustive: true
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - unused
        - bodyclose
        - gosec
run:
  skip-files:
    - generated.go
  skip-dirs:
    - xml