version: "2"
linters:
  enable:
    - bodyclose
    - errorlint
    - exhaustive
    - copyloopvar
    - goconst
    - gocritic
    - godot
    - gosec
    - makezero
    - misspell
    - nakedret
    - nestif
    - noctx
    - predeclared
    - unconvert
    - whitespace
  settings:
    gosec:
      excludes:
        - G204
    gocognit:
      min-complexity: 40
    nestif:
      min-complexity: 40
    exhaustive:
      default-signifies-exhaustive: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - goconst
          - unused
          - bodyclose
          - gosec
    paths:
      - generated.go
      - xml
