apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuesta-aggregator
spec:
  selector:
    matchLabels:
      app: kuesta-aggregator
  replicas: 1
  template:
    metadata:
      labels:
        app: kuesta-aggregator
    spec:
      containers:
        - name: kuesta
          image: kuesta:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/kuesta
          args:
            - device
            - aggregate
          env:
            - name: KUESTA_STATUS_ROOT_PATH
              value: /data/repo_status
            - name: KUESTA_STATUS_REPO_URL
              value: https://path/to/repo-status
            - name: KUESTA_INSECURE
              value: "true"
            - name: KUESTA_TLS_CRT
              value: /tmp/cert/tls.crt
            - name: KUESTA_TLS_KEY
              value: /tmp/cert/tls.key
            - name: KUESTA_TLS_CA_CRT
              value: /tmp/cert/ca.crt
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /data
              name: kuesta-aggregator-data
            - mountPath: /tmp/cert
              name: cert
              readOnly: true
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
      volumes:
        - name: kuesta-aggregator-data
          persistentVolumeClaim:
            claimName: kuesta-aggregator-data
        - name: cert
          secret:
            defaultMode: 420
            secretName: kuesta-aggregator-cert
