apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuesta-aggregator-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
