apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kuesta-server-cert
  namespace: kuesta-system
spec:
  dnsNames:
    - kuesta-server.kuesta-system.svc
    - kuesta-server.kuesta-system.svc.cluster.local
    - localhost
  issuerRef:
    kind: ClusterIssuer
    name: kuesta-ca-issuer
  secretName: kuesta-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kuesta-aggregator-cert
  namespace: kuesta-system
spec:
  dnsNames:
    - kuesta-aggregator.kuesta-system.svc
    - kuesta-aggregator.kuesta-system.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: kuesta-ca-issuer
  secretName: kuesta-aggregator-cert
