apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- kuesta-aggregator.deploy.yaml
- kuesta-aggregator.svc.yaml
- kuesta-aggregator.pvc.yaml
- kuesta-server.deploy.yaml
- kuesta-server.svc.yaml
- kuesta-server.pvc.yaml
- kuesta-cert.yaml

images:
- name: kuesta
  newName: ghcr.io/nttcom/kuesta/kuesta
  newTag: latest
