// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/nttcom/kuesta/testdata/types/pkg/ocdemo

package ocdemo

#Binary: bytes

#YANGEmpty: bool

#Device: {
	Interface: {[string]: null | #Interface} @go(,map[string]*Interface)
	Vlan: {[string]: null | #Vlan} @go(,map[string]*Vlan)
}

#Interface: {
	AdminStatus:  #E_Interface_AdminStatus
	Aggregation?: null | #Interface_Aggregation @go(,*Interface_Aggregation)
	Counters?:    null | #Interface_Counters    @go(,*Interface_Counters)
	Description?: null | string                 @go(,*string)
	Enabled?:     null | bool                   @go(,*bool)
	Ethernet?:    null | #Interface_Ethernet    @go(,*Interface_Ethernet)
	HoldTime?:    null | #Interface_HoldTime    @go(,*Interface_HoldTime)
	Ifindex?:     null | uint32                 @go(,*uint32)
	LastChange?:  null | uint32                 @go(,*uint32)
	Mtu?:         null | uint16                 @go(,*uint16)
	Name?:        null | string                 @go(,*string)
	OperStatus:   #E_Interface_OperStatus
	RoutedVlan?:  null | #Interface_RoutedVlan @go(,*Interface_RoutedVlan)
	Subinterface: {[string]: null | #Interface_Subinterface} @go(,map[string]*Interface_Subinterface)
	Type: #E_IETFInterfaces_InterfaceType
}

#Interface_Aggregation: {
	LagSpeed?: null | uint32 @go(,*uint32)
	LagType:   #E_OpenconfigIfAggregate_AggregationType
	Member: [...string] @go(,[]string)
	MinLinks?:     null | uint16                              @go(,*uint16)
	SwitchedVlan?: null | #Interface_Aggregation_SwitchedVlan @go(,*Interface_Aggregation_SwitchedVlan)
}

#Interface_Aggregation_SwitchedVlan: {
	AccessVlan:    #Interface_Aggregation_SwitchedVlan_AccessVlan_Union
	InterfaceMode: #E_OpenconfigVlanTypes_VlanModeType
	NativeVlan:    #Interface_Aggregation_SwitchedVlan_NativeVlan_Union
	TrunkVlans: [...#Interface_Aggregation_SwitchedVlan_TrunkVlans_Union] @go(,[]Interface_Aggregation_SwitchedVlan_TrunkVlans_Union)
}

#Interface_Aggregation_SwitchedVlan_AccessVlan_Union: _

#Interface_Aggregation_SwitchedVlan_AccessVlan_Union_String: String: string

#Interface_Aggregation_SwitchedVlan_AccessVlan_Union_Uint16: Uint16: uint16

#Interface_Aggregation_SwitchedVlan_NativeVlan_Union: _

#Interface_Aggregation_SwitchedVlan_NativeVlan_Union_String: String: string

#Interface_Aggregation_SwitchedVlan_NativeVlan_Union_Uint16: Uint16: uint16

#Interface_Aggregation_SwitchedVlan_TrunkVlans_Union: _

#Interface_Aggregation_SwitchedVlan_TrunkVlans_Union_String: String: string

#Interface_Aggregation_SwitchedVlan_TrunkVlans_Union_Uint16: Uint16: uint16

#Interface_Counters: {
	InBroadcastPkts?:  null | uint64 @go(,*uint64)
	InDiscards?:       null | uint64 @go(,*uint64)
	InErrors?:         null | uint64 @go(,*uint64)
	InMulticastPkts?:  null | uint64 @go(,*uint64)
	InOctets?:         null | uint64 @go(,*uint64)
	InUnicastPkts?:    null | uint64 @go(,*uint64)
	InUnknownProtos?:  null | uint32 @go(,*uint32)
	LastClear?:        null | string @go(,*string)
	OutBroadcastPkts?: null | uint64 @go(,*uint64)
	OutDiscards?:      null | uint64 @go(,*uint64)
	OutErrors?:        null | uint64 @go(,*uint64)
	OutMulticastPkts?: null | uint64 @go(,*uint64)
	OutOctets?:        null | uint64 @go(,*uint64)
	OutUnicastPkts?:   null | uint64 @go(,*uint64)
}

#Interface_Ethernet: {
	AggregateId?:         null | string                       @go(,*string)
	AutoNegotiate?:       null | bool                         @go(,*bool)
	Counters?:            null | #Interface_Ethernet_Counters @go(,*Interface_Ethernet_Counters)
	DuplexMode:           #E_Ethernet_DuplexMode
	EffectiveSpeed?:      null | uint32 @go(,*uint32)
	EnableFlowControl?:   null | bool   @go(,*bool)
	HwMacAddress?:        null | string @go(,*string)
	MacAddress?:          null | string @go(,*string)
	NegotiatedDuplexMode: #E_Ethernet_NegotiatedDuplexMode
	NegotiatedPortSpeed:  #E_OpenconfigIfEthernet_ETHERNET_SPEED
	PortSpeed:            #E_OpenconfigIfEthernet_ETHERNET_SPEED
	SwitchedVlan?:        null | #Interface_Ethernet_SwitchedVlan @go(,*Interface_Ethernet_SwitchedVlan)
}

#Interface_Ethernet_Counters: {
	In_8021QFrames?:      null | uint64 @go(,*uint64)
	InCrcErrors?:         null | uint64 @go(,*uint64)
	InFragmentFrames?:    null | uint64 @go(,*uint64)
	InJabberFrames?:      null | uint64 @go(,*uint64)
	InMacControlFrames?:  null | uint64 @go(,*uint64)
	InMacPauseFrames?:    null | uint64 @go(,*uint64)
	InOversizeFrames?:    null | uint64 @go(,*uint64)
	Out_8021QFrames?:     null | uint64 @go(,*uint64)
	OutMacControlFrames?: null | uint64 @go(,*uint64)
	OutMacPauseFrames?:   null | uint64 @go(,*uint64)
}

#Interface_Ethernet_SwitchedVlan: {
	AccessVlan:    #Interface_Ethernet_SwitchedVlan_AccessVlan_Union
	InterfaceMode: #E_OpenconfigVlanTypes_VlanModeType
	NativeVlan:    #Interface_Ethernet_SwitchedVlan_NativeVlan_Union
	TrunkVlans: [...#Interface_Ethernet_SwitchedVlan_TrunkVlans_Union] @go(,[]Interface_Ethernet_SwitchedVlan_TrunkVlans_Union)
}

#Interface_Ethernet_SwitchedVlan_AccessVlan_Union: _

#Interface_Ethernet_SwitchedVlan_AccessVlan_Union_String: String: string

#Interface_Ethernet_SwitchedVlan_AccessVlan_Union_Uint16: Uint16: uint16

#Interface_Ethernet_SwitchedVlan_NativeVlan_Union: _

#Interface_Ethernet_SwitchedVlan_NativeVlan_Union_String: String: string

#Interface_Ethernet_SwitchedVlan_NativeVlan_Union_Uint16: Uint16: uint16

#Interface_Ethernet_SwitchedVlan_TrunkVlans_Union: _

#Interface_Ethernet_SwitchedVlan_TrunkVlans_Union_String: String: string

#Interface_Ethernet_SwitchedVlan_TrunkVlans_Union_Uint16: Uint16: uint16

#Interface_HoldTime: {
	Down?: null | uint32 @go(,*uint32)
	Up?:   null | uint32 @go(,*uint32)
}

#Interface_RoutedVlan: {
	Ipv4?: null | #Interface_RoutedVlan_Ipv4 @go(,*Interface_RoutedVlan_Ipv4)
	Ipv6?: null | #Interface_RoutedVlan_Ipv6 @go(,*Interface_RoutedVlan_Ipv6)
	Vlan:  #Interface_RoutedVlan_Vlan_Union
}

#Interface_RoutedVlan_Vlan_Union: _

#Interface_RoutedVlan_Vlan_Union_String: String: string

#Interface_RoutedVlan_Vlan_Union_Uint16: Uint16: uint16

#Interface_RoutedVlan_Ipv4: {
	Address: {[string]: null | #Interface_RoutedVlan_Ipv4_Address} @go(,map[string]*Interface_RoutedVlan_Ipv4_Address)
	Enabled?: null | bool   @go(,*bool)
	Mtu?:     null | uint16 @go(,*uint16)
	Neighbor: {[string]: null | #Interface_RoutedVlan_Ipv4_Neighbor} @go(,map[string]*Interface_RoutedVlan_Ipv4_Neighbor)
	Unnumbered?: null | #Interface_RoutedVlan_Ipv4_Unnumbered @go(,*Interface_RoutedVlan_Ipv4_Unnumbered)
}

#Interface_RoutedVlan_Ipv4_Address: {
	Ip?:           null | string @go(,*string)
	Origin:        #E_OpenconfigIfIp_IpAddressOrigin
	PrefixLength?: null | uint8 @go(,*uint8)
	VrrpGroup: {[string]: null | #Interface_RoutedVlan_Ipv4_Address_VrrpGroup} @go(,map[string]*Interface_RoutedVlan_Ipv4_Address_VrrpGroup)
}

#Interface_RoutedVlan_Ipv4_Address_VrrpGroup: {
	AcceptMode?:            null | bool                                                           @go(,*bool)
	AdvertisementInterval?: null | uint16                                                         @go(,*uint16)
	CurrentPriority?:       null | uint8                                                          @go(,*uint8)
	InterfaceTracking?:     null | #Interface_RoutedVlan_Ipv4_Address_VrrpGroup_InterfaceTracking @go(,*Interface_RoutedVlan_Ipv4_Address_VrrpGroup_InterfaceTracking)
	Preempt?:               null | bool                                                           @go(,*bool)
	PreemptDelay?:          null | uint16                                                         @go(,*uint16)
	Priority?:              null | uint8                                                          @go(,*uint8)
	VirtualAddress: [...string] @go(,[]string)
	VirtualRouterId?: null | uint8 @go(,*uint8)
}

#Interface_RoutedVlan_Ipv4_Address_VrrpGroup_InterfaceTracking: {
	PriorityDecrement?: null | uint8  @go(,*uint8)
	TrackInterface?:    null | string @go(,*string)
}

#Interface_RoutedVlan_Ipv4_Neighbor: {
	Ip?:               null | string @go(,*string)
	LinkLayerAddress?: null | string @go(,*string)
	Origin:            #E_OpenconfigIfIp_NeighborOrigin
}

#Interface_RoutedVlan_Ipv4_Unnumbered: {
	Enabled?:      null | bool                                               @go(,*bool)
	InterfaceRef?: null | #Interface_RoutedVlan_Ipv4_Unnumbered_InterfaceRef @go(,*Interface_RoutedVlan_Ipv4_Unnumbered_InterfaceRef)
}

#Interface_RoutedVlan_Ipv4_Unnumbered_InterfaceRef: {
	Interface?:    null | string @go(,*string)
	Subinterface?: null | uint32 @go(,*uint32)
}

#Interface_RoutedVlan_Ipv6: {
	Address: {[string]: null | #Interface_RoutedVlan_Ipv6_Address} @go(,map[string]*Interface_RoutedVlan_Ipv6_Address)
	DupAddrDetectTransmits?: null | uint32 @go(,*uint32)
	Enabled?:                null | bool   @go(,*bool)
	Mtu?:                    null | uint32 @go(,*uint32)
	Neighbor: {[string]: null | #Interface_RoutedVlan_Ipv6_Neighbor} @go(,map[string]*Interface_RoutedVlan_Ipv6_Neighbor)
	Unnumbered?: null | #Interface_RoutedVlan_Ipv6_Unnumbered @go(,*Interface_RoutedVlan_Ipv6_Unnumbered)
}

#Interface_RoutedVlan_Ipv6_Address: {
	Ip?:           null | string @go(,*string)
	Origin:        #E_OpenconfigIfIp_IpAddressOrigin
	PrefixLength?: null | uint8 @go(,*uint8)
	Status:        #E_Address_Status
	VrrpGroup: {[string]: null | #Interface_RoutedVlan_Ipv6_Address_VrrpGroup} @go(,map[string]*Interface_RoutedVlan_Ipv6_Address_VrrpGroup)
}

#Interface_RoutedVlan_Ipv6_Address_VrrpGroup: {
	AcceptMode?:            null | bool                                                           @go(,*bool)
	AdvertisementInterval?: null | uint16                                                         @go(,*uint16)
	CurrentPriority?:       null | uint8                                                          @go(,*uint8)
	InterfaceTracking?:     null | #Interface_RoutedVlan_Ipv6_Address_VrrpGroup_InterfaceTracking @go(,*Interface_RoutedVlan_Ipv6_Address_VrrpGroup_InterfaceTracking)
	Preempt?:               null | bool                                                           @go(,*bool)
	PreemptDelay?:          null | uint16                                                         @go(,*uint16)
	Priority?:              null | uint8                                                          @go(,*uint8)
	VirtualAddress: [...string] @go(,[]string)
	VirtualLinkLocal?: null | string @go(,*string)
	VirtualRouterId?:  null | uint8  @go(,*uint8)
}

#Interface_RoutedVlan_Ipv6_Address_VrrpGroup_InterfaceTracking: {
	PriorityDecrement?: null | uint8  @go(,*uint8)
	TrackInterface?:    null | string @go(,*string)
}

#Interface_RoutedVlan_Ipv6_Neighbor: {
	Ip?:               null | string @go(,*string)
	IsRouter:          #YANGEmpty
	LinkLayerAddress?: null | string @go(,*string)
	NeighborState:     #E_Neighbor_NeighborState
	Origin:            #E_OpenconfigIfIp_NeighborOrigin
}

#Interface_RoutedVlan_Ipv6_Unnumbered: {
	Enabled?:      null | bool                                               @go(,*bool)
	InterfaceRef?: null | #Interface_RoutedVlan_Ipv6_Unnumbered_InterfaceRef @go(,*Interface_RoutedVlan_Ipv6_Unnumbered_InterfaceRef)
}

#Interface_RoutedVlan_Ipv6_Unnumbered_InterfaceRef: {
	Interface?:    null | string @go(,*string)
	Subinterface?: null | uint32 @go(,*uint32)
}

#Interface_Subinterface: {
	AdminStatus:  #E_Interface_AdminStatus
	Counters?:    null | #Interface_Subinterface_Counters @go(,*Interface_Subinterface_Counters)
	Description?: null | string                           @go(,*string)
	Enabled?:     null | bool                             @go(,*bool)
	Ifindex?:     null | uint32                           @go(,*uint32)
	Index?:       null | uint32                           @go(,*uint32)
	Ipv4?:        null | #Interface_Subinterface_Ipv4     @go(,*Interface_Subinterface_Ipv4)
	Ipv6?:        null | #Interface_Subinterface_Ipv6     @go(,*Interface_Subinterface_Ipv6)
	LastChange?:  null | uint32                           @go(,*uint32)
	Name?:        null | string                           @go(,*string)
	OperStatus:   #E_Interface_OperStatus
	Vlan?:        null | #Interface_Subinterface_Vlan @go(,*Interface_Subinterface_Vlan)
}

#Interface_Subinterface_Counters: {
	InBroadcastPkts?:  null | uint64 @go(,*uint64)
	InDiscards?:       null | uint64 @go(,*uint64)
	InErrors?:         null | uint64 @go(,*uint64)
	InMulticastPkts?:  null | uint64 @go(,*uint64)
	InOctets?:         null | uint64 @go(,*uint64)
	InUnicastPkts?:    null | uint64 @go(,*uint64)
	InUnknownProtos?:  null | uint32 @go(,*uint32)
	LastClear?:        null | string @go(,*string)
	OutBroadcastPkts?: null | uint64 @go(,*uint64)
	OutDiscards?:      null | uint64 @go(,*uint64)
	OutErrors?:        null | uint64 @go(,*uint64)
	OutMulticastPkts?: null | uint64 @go(,*uint64)
	OutOctets?:        null | uint64 @go(,*uint64)
	OutUnicastPkts?:   null | uint64 @go(,*uint64)
}

#Interface_Subinterface_Ipv4: {
	Address: {[string]: null | #Interface_Subinterface_Ipv4_Address} @go(,map[string]*Interface_Subinterface_Ipv4_Address)
	Enabled?: null | bool   @go(,*bool)
	Mtu?:     null | uint16 @go(,*uint16)
	Neighbor: {[string]: null | #Interface_Subinterface_Ipv4_Neighbor} @go(,map[string]*Interface_Subinterface_Ipv4_Neighbor)
	Unnumbered?: null | #Interface_Subinterface_Ipv4_Unnumbered @go(,*Interface_Subinterface_Ipv4_Unnumbered)
}

#Interface_Subinterface_Ipv4_Address: {
	Ip?:           null | string @go(,*string)
	Origin:        #E_OpenconfigIfIp_IpAddressOrigin
	PrefixLength?: null | uint8 @go(,*uint8)
	VrrpGroup: {[string]: null | #Interface_Subinterface_Ipv4_Address_VrrpGroup} @go(,map[string]*Interface_Subinterface_Ipv4_Address_VrrpGroup)
}

#Interface_Subinterface_Ipv4_Address_VrrpGroup: {
	AcceptMode?:            null | bool                                                             @go(,*bool)
	AdvertisementInterval?: null | uint16                                                           @go(,*uint16)
	CurrentPriority?:       null | uint8                                                            @go(,*uint8)
	InterfaceTracking?:     null | #Interface_Subinterface_Ipv4_Address_VrrpGroup_InterfaceTracking @go(,*Interface_Subinterface_Ipv4_Address_VrrpGroup_InterfaceTracking)
	Preempt?:               null | bool                                                             @go(,*bool)
	PreemptDelay?:          null | uint16                                                           @go(,*uint16)
	Priority?:              null | uint8                                                            @go(,*uint8)
	VirtualAddress: [...string] @go(,[]string)
	VirtualRouterId?: null | uint8 @go(,*uint8)
}

#Interface_Subinterface_Ipv4_Address_VrrpGroup_InterfaceTracking: {
	PriorityDecrement?: null | uint8  @go(,*uint8)
	TrackInterface?:    null | string @go(,*string)
}

#Interface_Subinterface_Ipv4_Neighbor: {
	Ip?:               null | string @go(,*string)
	LinkLayerAddress?: null | string @go(,*string)
	Origin:            #E_OpenconfigIfIp_NeighborOrigin
}

#Interface_Subinterface_Ipv4_Unnumbered: {
	Enabled?:      null | bool                                                 @go(,*bool)
	InterfaceRef?: null | #Interface_Subinterface_Ipv4_Unnumbered_InterfaceRef @go(,*Interface_Subinterface_Ipv4_Unnumbered_InterfaceRef)
}

#Interface_Subinterface_Ipv4_Unnumbered_InterfaceRef: {
	Interface?:    null | string @go(,*string)
	Subinterface?: null | uint32 @go(,*uint32)
}

#Interface_Subinterface_Ipv6: {
	Address: {[string]: null | #Interface_Subinterface_Ipv6_Address} @go(,map[string]*Interface_Subinterface_Ipv6_Address)
	DupAddrDetectTransmits?: null | uint32 @go(,*uint32)
	Enabled?:                null | bool   @go(,*bool)
	Mtu?:                    null | uint32 @go(,*uint32)
	Neighbor: {[string]: null | #Interface_Subinterface_Ipv6_Neighbor} @go(,map[string]*Interface_Subinterface_Ipv6_Neighbor)
	Unnumbered?: null | #Interface_Subinterface_Ipv6_Unnumbered @go(,*Interface_Subinterface_Ipv6_Unnumbered)
}

#Interface_Subinterface_Ipv6_Address: {
	Ip?:           null | string @go(,*string)
	Origin:        #E_OpenconfigIfIp_IpAddressOrigin
	PrefixLength?: null | uint8 @go(,*uint8)
	Status:        #E_Address_Status
	VrrpGroup: {[string]: null | #Interface_Subinterface_Ipv6_Address_VrrpGroup} @go(,map[string]*Interface_Subinterface_Ipv6_Address_VrrpGroup)
}

#Interface_Subinterface_Ipv6_Address_VrrpGroup: {
	AcceptMode?:            null | bool                                                             @go(,*bool)
	AdvertisementInterval?: null | uint16                                                           @go(,*uint16)
	CurrentPriority?:       null | uint8                                                            @go(,*uint8)
	InterfaceTracking?:     null | #Interface_Subinterface_Ipv6_Address_VrrpGroup_InterfaceTracking @go(,*Interface_Subinterface_Ipv6_Address_VrrpGroup_InterfaceTracking)
	Preempt?:               null | bool                                                             @go(,*bool)
	PreemptDelay?:          null | uint16                                                           @go(,*uint16)
	Priority?:              null | uint8                                                            @go(,*uint8)
	VirtualAddress: [...string] @go(,[]string)
	VirtualLinkLocal?: null | string @go(,*string)
	VirtualRouterId?:  null | uint8  @go(,*uint8)
}

#Interface_Subinterface_Ipv6_Address_VrrpGroup_InterfaceTracking: {
	PriorityDecrement?: null | uint8  @go(,*uint8)
	TrackInterface?:    null | string @go(,*string)
}

#Interface_Subinterface_Ipv6_Neighbor: {
	Ip?:               null | string @go(,*string)
	IsRouter:          #YANGEmpty
	LinkLayerAddress?: null | string @go(,*string)
	NeighborState:     #E_Neighbor_NeighborState
	Origin:            #E_OpenconfigIfIp_NeighborOrigin
}

#Interface_Subinterface_Ipv6_Unnumbered: {
	Enabled?:      null | bool                                                 @go(,*bool)
	InterfaceRef?: null | #Interface_Subinterface_Ipv6_Unnumbered_InterfaceRef @go(,*Interface_Subinterface_Ipv6_Unnumbered_InterfaceRef)
}

#Interface_Subinterface_Ipv6_Unnumbered_InterfaceRef: {
	Interface?:    null | string @go(,*string)
	Subinterface?: null | uint32 @go(,*uint32)
}

#Interface_Subinterface_Vlan: VlanId: #Interface_Subinterface_Vlan_VlanId_Union

#Interface_Subinterface_Vlan_VlanId_Union: _

#Interface_Subinterface_Vlan_VlanId_Union_String: String: string

#Interface_Subinterface_Vlan_VlanId_Union_Uint16: Uint16: uint16

#Vlan: {
	Member: [...null | #Vlan_Member] @go(,[]*Vlan_Member)
	Name?:   null | string @go(,*string)
	Status:  #E_Vlan_Status
	Tpid:    #E_OpenconfigVlanTypes_TPID_TYPES
	VlanId?: null | uint16 @go(,*uint16)
}

#Vlan_Member: {
	InterfaceRef?: null | #Vlan_Member_InterfaceRef @go(,*Vlan_Member_InterfaceRef)
}

#Vlan_Member_InterfaceRef: {
	Interface?:    null | string @go(,*string)
	Subinterface?: null | uint32 @go(,*uint32)
}

#E_Address_Status: int64 // #enumE_Address_Status

#enumE_Address_Status:
	#Address_Status_UNSET |
	#Address_Status_PREFERRED |
	#Address_Status_DEPRECATED |
	#Address_Status_INVALID |
	#Address_Status_INACCESSIBLE |
	#Address_Status_UNKNOWN |
	#Address_Status_TENTATIVE |
	#Address_Status_DUPLICATE |
	#Address_Status_OPTIMISTIC

#values_E_Address_Status: {
	Address_Status_UNSET:        #Address_Status_UNSET
	Address_Status_PREFERRED:    #Address_Status_PREFERRED
	Address_Status_DEPRECATED:   #Address_Status_DEPRECATED
	Address_Status_INVALID:      #Address_Status_INVALID
	Address_Status_INACCESSIBLE: #Address_Status_INACCESSIBLE
	Address_Status_UNKNOWN:      #Address_Status_UNKNOWN
	Address_Status_TENTATIVE:    #Address_Status_TENTATIVE
	Address_Status_DUPLICATE:    #Address_Status_DUPLICATE
	Address_Status_OPTIMISTIC:   #Address_Status_OPTIMISTIC
}

#Address_Status_UNSET:        #E_Address_Status & 0
#Address_Status_PREFERRED:    #E_Address_Status & 1
#Address_Status_DEPRECATED:   #E_Address_Status & 2
#Address_Status_INVALID:      #E_Address_Status & 3
#Address_Status_INACCESSIBLE: #E_Address_Status & 4
#Address_Status_UNKNOWN:      #E_Address_Status & 5
#Address_Status_TENTATIVE:    #E_Address_Status & 6
#Address_Status_DUPLICATE:    #E_Address_Status & 7
#Address_Status_OPTIMISTIC:   #E_Address_Status & 8

#E_Ethernet_DuplexMode: int64 // #enumE_Ethernet_DuplexMode

#enumE_Ethernet_DuplexMode:
	#Ethernet_DuplexMode_UNSET |
	#Ethernet_DuplexMode_FULL |
	#Ethernet_DuplexMode_HALF

#values_E_Ethernet_DuplexMode: {
	Ethernet_DuplexMode_UNSET: #Ethernet_DuplexMode_UNSET
	Ethernet_DuplexMode_FULL:  #Ethernet_DuplexMode_FULL
	Ethernet_DuplexMode_HALF:  #Ethernet_DuplexMode_HALF
}

#Ethernet_DuplexMode_UNSET: #E_Ethernet_DuplexMode & 0
#Ethernet_DuplexMode_FULL:  #E_Ethernet_DuplexMode & 1
#Ethernet_DuplexMode_HALF:  #E_Ethernet_DuplexMode & 2

#E_Ethernet_NegotiatedDuplexMode: int64 // #enumE_Ethernet_NegotiatedDuplexMode

#enumE_Ethernet_NegotiatedDuplexMode:
	#Ethernet_NegotiatedDuplexMode_UNSET |
	#Ethernet_NegotiatedDuplexMode_FULL |
	#Ethernet_NegotiatedDuplexMode_HALF

#values_E_Ethernet_NegotiatedDuplexMode: {
	Ethernet_NegotiatedDuplexMode_UNSET: #Ethernet_NegotiatedDuplexMode_UNSET
	Ethernet_NegotiatedDuplexMode_FULL:  #Ethernet_NegotiatedDuplexMode_FULL
	Ethernet_NegotiatedDuplexMode_HALF:  #Ethernet_NegotiatedDuplexMode_HALF
}

#Ethernet_NegotiatedDuplexMode_UNSET: #E_Ethernet_NegotiatedDuplexMode & 0
#Ethernet_NegotiatedDuplexMode_FULL:  #E_Ethernet_NegotiatedDuplexMode & 1
#Ethernet_NegotiatedDuplexMode_HALF:  #E_Ethernet_NegotiatedDuplexMode & 2

#E_IETFInterfaces_InterfaceType: int64 // #enumE_IETFInterfaces_InterfaceType

#enumE_IETFInterfaces_InterfaceType:
	#IETFInterfaces_InterfaceType_UNSET |
	#IETFInterfaces_InterfaceType_a12MppSwitch |
	#IETFInterfaces_InterfaceType_aal2 |
	#IETFInterfaces_InterfaceType_aal5 |
	#IETFInterfaces_InterfaceType_actelisMetaLOOP |
	#IETFInterfaces_InterfaceType_adsl |
	#IETFInterfaces_InterfaceType_adsl2 |
	#IETFInterfaces_InterfaceType_adsl2plus |
	#IETFInterfaces_InterfaceType_aflane8023 |
	#IETFInterfaces_InterfaceType_aflane8025 |
	#IETFInterfaces_InterfaceType_aluELP |
	#IETFInterfaces_InterfaceType_aluEpon |
	#IETFInterfaces_InterfaceType_aluEponLogicalLink |
	#IETFInterfaces_InterfaceType_aluEponOnu |
	#IETFInterfaces_InterfaceType_aluEponPhysicalUni |
	#IETFInterfaces_InterfaceType_aluGponOnu |
	#IETFInterfaces_InterfaceType_aluGponPhysicalUni |
	#IETFInterfaces_InterfaceType_arap |
	#IETFInterfaces_InterfaceType_arcnet |
	#IETFInterfaces_InterfaceType_arcnetPlus |
	#IETFInterfaces_InterfaceType_async |
	#IETFInterfaces_InterfaceType_atm |
	#IETFInterfaces_InterfaceType_atmDxi |
	#IETFInterfaces_InterfaceType_atmFuni |
	#IETFInterfaces_InterfaceType_atmIma |
	#IETFInterfaces_InterfaceType_atmLogical |
	#IETFInterfaces_InterfaceType_atmRadio |
	#IETFInterfaces_InterfaceType_atmSubInterface |
	#IETFInterfaces_InterfaceType_atmVciEndPt |
	#IETFInterfaces_InterfaceType_atmVirtual |
	#IETFInterfaces_InterfaceType_atmbond |
	#IETFInterfaces_InterfaceType_aviciOpticalEther |
	#IETFInterfaces_InterfaceType_basicISDN |
	#IETFInterfaces_InterfaceType_bgppolicyaccounting |
	#IETFInterfaces_InterfaceType_bits |
	#IETFInterfaces_InterfaceType_bridge |
	#IETFInterfaces_InterfaceType_bsc |
	#IETFInterfaces_InterfaceType_cableDownstreamRfPort |
	#IETFInterfaces_InterfaceType_capwapDot11Bss |
	#IETFInterfaces_InterfaceType_capwapDot11Profile |
	#IETFInterfaces_InterfaceType_capwapWtpVirtualRadio |
	#IETFInterfaces_InterfaceType_cblVectaStar |
	#IETFInterfaces_InterfaceType_cctEmul |
	#IETFInterfaces_InterfaceType_ces |
	#IETFInterfaces_InterfaceType_channel |
	#IETFInterfaces_InterfaceType_ciscoISLvlan |
	#IETFInterfaces_InterfaceType_cnr |
	#IETFInterfaces_InterfaceType_coffee |
	#IETFInterfaces_InterfaceType_compositeLink |
	#IETFInterfaces_InterfaceType_dcn |
	#IETFInterfaces_InterfaceType_ddnX25 |
	#IETFInterfaces_InterfaceType_digitalPowerline |
	#IETFInterfaces_InterfaceType_digitalWrapperOverheadChannel |
	#IETFInterfaces_InterfaceType_dlsw |
	#IETFInterfaces_InterfaceType_docsCableDownstream |
	#IETFInterfaces_InterfaceType_docsCableMCmtsDownstream |
	#IETFInterfaces_InterfaceType_docsCableMaclayer |
	#IETFInterfaces_InterfaceType_docsCableUpstream |
	#IETFInterfaces_InterfaceType_docsCableUpstreamChannel |
	#IETFInterfaces_InterfaceType_docsCableUpstreamRfPort |
	#IETFInterfaces_InterfaceType_ds0 |
	#IETFInterfaces_InterfaceType_ds0Bundle |
	#IETFInterfaces_InterfaceType_ds1 |
	#IETFInterfaces_InterfaceType_ds1FDL |
	#IETFInterfaces_InterfaceType_ds3 |
	#IETFInterfaces_InterfaceType_dtm |
	#IETFInterfaces_InterfaceType_dvbAsiIn |
	#IETFInterfaces_InterfaceType_dvbAsiOut |
	#IETFInterfaces_InterfaceType_dvbRccDownstream |
	#IETFInterfaces_InterfaceType_dvbRccMacLayer |
	#IETFInterfaces_InterfaceType_dvbRccUpstream |
	#IETFInterfaces_InterfaceType_dvbRcsMacLayer |
	#IETFInterfaces_InterfaceType_dvbRcsTdma |
	#IETFInterfaces_InterfaceType_dvbTdm |
	#IETFInterfaces_InterfaceType_e1 |
	#IETFInterfaces_InterfaceType_econet |
	#IETFInterfaces_InterfaceType_eon |
	#IETFInterfaces_InterfaceType_eplrs |
	#IETFInterfaces_InterfaceType_escon |
	#IETFInterfaces_InterfaceType_ethernet3Mbit |
	#IETFInterfaces_InterfaceType_ethernetCsmacd |
	#IETFInterfaces_InterfaceType_fast |
	#IETFInterfaces_InterfaceType_fastEther |
	#IETFInterfaces_InterfaceType_fastEtherFX |
	#IETFInterfaces_InterfaceType_fcipLink |
	#IETFInterfaces_InterfaceType_fddi |
	#IETFInterfaces_InterfaceType_fibreChannel |
	#IETFInterfaces_InterfaceType_frDlciEndPt |
	#IETFInterfaces_InterfaceType_frForward |
	#IETFInterfaces_InterfaceType_frameRelay |
	#IETFInterfaces_InterfaceType_frameRelayInterconnect |
	#IETFInterfaces_InterfaceType_frameRelayMPI |
	#IETFInterfaces_InterfaceType_frameRelayService |
	#IETFInterfaces_InterfaceType_frf16MfrBundle |
	#IETFInterfaces_InterfaceType_g703at2mb |
	#IETFInterfaces_InterfaceType_g703at64k |
	#IETFInterfaces_InterfaceType_g9981 |
	#IETFInterfaces_InterfaceType_g9982 |
	#IETFInterfaces_InterfaceType_g9983 |
	#IETFInterfaces_InterfaceType_gfp |
	#IETFInterfaces_InterfaceType_gigabitEthernet |
	#IETFInterfaces_InterfaceType_gpon |
	#IETFInterfaces_InterfaceType_gr303IDT |
	#IETFInterfaces_InterfaceType_gr303RDT |
	#IETFInterfaces_InterfaceType_gtp |
	#IETFInterfaces_InterfaceType_h323Gatekeeper |
	#IETFInterfaces_InterfaceType_h323Proxy |
	#IETFInterfaces_InterfaceType_hdh1822 |
	#IETFInterfaces_InterfaceType_hdlc |
	#IETFInterfaces_InterfaceType_hdsl2 |
	#IETFInterfaces_InterfaceType_hiperlan2 |
	#IETFInterfaces_InterfaceType_hippi |
	#IETFInterfaces_InterfaceType_hippiInterface |
	#IETFInterfaces_InterfaceType_homepna |
	#IETFInterfaces_InterfaceType_hostPad |
	#IETFInterfaces_InterfaceType_hssi |
	#IETFInterfaces_InterfaceType_hyperchannel |
	#IETFInterfaces_InterfaceType_iana_interface_type |
	#IETFInterfaces_InterfaceType_ibm370parChan |
	#IETFInterfaces_InterfaceType_idsl |
	#IETFInterfaces_InterfaceType_ieee1394 |
	#IETFInterfaces_InterfaceType_ieee80211 |
	#IETFInterfaces_InterfaceType_ieee80212 |
	#IETFInterfaces_InterfaceType_ieee802154 |
	#IETFInterfaces_InterfaceType_ieee80216WMAN |
	#IETFInterfaces_InterfaceType_ieee8023adLag |
	#IETFInterfaces_InterfaceType_if_gsn |
	#IETFInterfaces_InterfaceType_ifPwType |
	#IETFInterfaces_InterfaceType_ifVfiType |
	#IETFInterfaces_InterfaceType_ilan |
	#IETFInterfaces_InterfaceType_imt |
	#IETFInterfaces_InterfaceType_infiniband |
	#IETFInterfaces_InterfaceType_interleave |
	#IETFInterfaces_InterfaceType_ip |
	#IETFInterfaces_InterfaceType_ipForward |
	#IETFInterfaces_InterfaceType_ipOverAtm |
	#IETFInterfaces_InterfaceType_ipOverCdlc |
	#IETFInterfaces_InterfaceType_ipOverClaw |
	#IETFInterfaces_InterfaceType_ipSwitch |
	#IETFInterfaces_InterfaceType_isdn |
	#IETFInterfaces_InterfaceType_isdns |
	#IETFInterfaces_InterfaceType_isdnu |
	#IETFInterfaces_InterfaceType_iso88022llc |
	#IETFInterfaces_InterfaceType_iso88023Csmacd |
	#IETFInterfaces_InterfaceType_iso88024TokenBus |
	#IETFInterfaces_InterfaceType_iso88025CRFPInt |
	#IETFInterfaces_InterfaceType_iso88025Dtr |
	#IETFInterfaces_InterfaceType_iso88025Fiber |
	#IETFInterfaces_InterfaceType_iso88025TokenRing |
	#IETFInterfaces_InterfaceType_iso88026Man |
	#IETFInterfaces_InterfaceType_isup |
	#IETFInterfaces_InterfaceType_l2vlan |
	#IETFInterfaces_InterfaceType_l3ipvlan |
	#IETFInterfaces_InterfaceType_l3ipxvlan |
	#IETFInterfaces_InterfaceType_lapb |
	#IETFInterfaces_InterfaceType_lapd |
	#IETFInterfaces_InterfaceType_lapf |
	#IETFInterfaces_InterfaceType_linegroup |
	#IETFInterfaces_InterfaceType_lmp |
	#IETFInterfaces_InterfaceType_localTalk |
	#IETFInterfaces_InterfaceType_macSecControlledIF |
	#IETFInterfaces_InterfaceType_macSecUncontrolledIF |
	#IETFInterfaces_InterfaceType_mediaMailOverIp |
	#IETFInterfaces_InterfaceType_mfSigLink |
	#IETFInterfaces_InterfaceType_miox25 |
	#IETFInterfaces_InterfaceType_mocaVersion1 |
	#IETFInterfaces_InterfaceType_modem |
	#IETFInterfaces_InterfaceType_mpc |
	#IETFInterfaces_InterfaceType_mpegTransport |
	#IETFInterfaces_InterfaceType_mpls |
	#IETFInterfaces_InterfaceType_mplsTunnel |
	#IETFInterfaces_InterfaceType_msdsl |
	#IETFInterfaces_InterfaceType_mvl |
	#IETFInterfaces_InterfaceType_myrinet |
	#IETFInterfaces_InterfaceType_nfas |
	#IETFInterfaces_InterfaceType_nsip |
	#IETFInterfaces_InterfaceType_opticalChannel |
	#IETFInterfaces_InterfaceType_opticalChannelGroup |
	#IETFInterfaces_InterfaceType_opticalTransport |
	#IETFInterfaces_InterfaceType_other |
	#IETFInterfaces_InterfaceType_otnOdu |
	#IETFInterfaces_InterfaceType_otnOtu |
	#IETFInterfaces_InterfaceType_para |
	#IETFInterfaces_InterfaceType_pdnEtherLoop1 |
	#IETFInterfaces_InterfaceType_pdnEtherLoop2 |
	#IETFInterfaces_InterfaceType_pip |
	#IETFInterfaces_InterfaceType_plc |
	#IETFInterfaces_InterfaceType_pon155 |
	#IETFInterfaces_InterfaceType_pon622 |
	#IETFInterfaces_InterfaceType_pos |
	#IETFInterfaces_InterfaceType_ppp |
	#IETFInterfaces_InterfaceType_pppMultilinkBundle |
	#IETFInterfaces_InterfaceType_primaryISDN |
	#IETFInterfaces_InterfaceType_propAtm |
	#IETFInterfaces_InterfaceType_propBWAp2Mp |
	#IETFInterfaces_InterfaceType_propCnls |
	#IETFInterfaces_InterfaceType_propDocsWirelessDownstream |
	#IETFInterfaces_InterfaceType_propDocsWirelessMaclayer |
	#IETFInterfaces_InterfaceType_propDocsWirelessUpstream |
	#IETFInterfaces_InterfaceType_propMultiplexor |
	#IETFInterfaces_InterfaceType_propPointToPointSerial |
	#IETFInterfaces_InterfaceType_propVirtual |
	#IETFInterfaces_InterfaceType_propWirelessP2P |
	#IETFInterfaces_InterfaceType_proteon10Mbit |
	#IETFInterfaces_InterfaceType_proteon80Mbit |
	#IETFInterfaces_InterfaceType_q2931 |
	#IETFInterfaces_InterfaceType_qam |
	#IETFInterfaces_InterfaceType_qllc |
	#IETFInterfaces_InterfaceType_radioMAC |
	#IETFInterfaces_InterfaceType_radsl |
	#IETFInterfaces_InterfaceType_reachDSL |
	#IETFInterfaces_InterfaceType_regular1822 |
	#IETFInterfaces_InterfaceType_rfc1483 |
	#IETFInterfaces_InterfaceType_rfc877x25 |
	#IETFInterfaces_InterfaceType_rpr |
	#IETFInterfaces_InterfaceType_rs232 |
	#IETFInterfaces_InterfaceType_rsrb |
	#IETFInterfaces_InterfaceType_sdlc |
	#IETFInterfaces_InterfaceType_sdsl |
	#IETFInterfaces_InterfaceType_shdsl |
	#IETFInterfaces_InterfaceType_sip |
	#IETFInterfaces_InterfaceType_sipSig |
	#IETFInterfaces_InterfaceType_sipTg |
	#IETFInterfaces_InterfaceType_sixToFour |
	#IETFInterfaces_InterfaceType_slip |
	#IETFInterfaces_InterfaceType_smdsDxi |
	#IETFInterfaces_InterfaceType_smdsIcip |
	#IETFInterfaces_InterfaceType_softwareLoopback |
	#IETFInterfaces_InterfaceType_sonet |
	#IETFInterfaces_InterfaceType_sonetOverheadChannel |
	#IETFInterfaces_InterfaceType_sonetPath |
	#IETFInterfaces_InterfaceType_sonetVT |
	#IETFInterfaces_InterfaceType_srp |
	#IETFInterfaces_InterfaceType_ss7SigLink |
	#IETFInterfaces_InterfaceType_stackToStack |
	#IETFInterfaces_InterfaceType_starLan |
	#IETFInterfaces_InterfaceType_tdlc |
	#IETFInterfaces_InterfaceType_teLink |
	#IETFInterfaces_InterfaceType_termPad |
	#IETFInterfaces_InterfaceType_tr008 |
	#IETFInterfaces_InterfaceType_transpHdlc |
	#IETFInterfaces_InterfaceType_tunnel |
	#IETFInterfaces_InterfaceType_ultra |
	#IETFInterfaces_InterfaceType_usb |
	#IETFInterfaces_InterfaceType_v11 |
	#IETFInterfaces_InterfaceType_v35 |
	#IETFInterfaces_InterfaceType_v36 |
	#IETFInterfaces_InterfaceType_v37 |
	#IETFInterfaces_InterfaceType_vdsl |
	#IETFInterfaces_InterfaceType_vdsl2 |
	#IETFInterfaces_InterfaceType_virtualIpAddress |
	#IETFInterfaces_InterfaceType_virtualTg |
	#IETFInterfaces_InterfaceType_vmwareNicTeam |
	#IETFInterfaces_InterfaceType_vmwareVirtualNic |
	#IETFInterfaces_InterfaceType_voiceDID |
	#IETFInterfaces_InterfaceType_voiceEBS |
	#IETFInterfaces_InterfaceType_voiceEM |
	#IETFInterfaces_InterfaceType_voiceEMFGD |
	#IETFInterfaces_InterfaceType_voiceEncap |
	#IETFInterfaces_InterfaceType_voiceFGDEANA |
	#IETFInterfaces_InterfaceType_voiceFGDOS |
	#IETFInterfaces_InterfaceType_voiceFXO |
	#IETFInterfaces_InterfaceType_voiceFXS |
	#IETFInterfaces_InterfaceType_voiceOverAtm |
	#IETFInterfaces_InterfaceType_voiceOverCable |
	#IETFInterfaces_InterfaceType_voiceOverFrameRelay |
	#IETFInterfaces_InterfaceType_voiceOverIp |
	#IETFInterfaces_InterfaceType_wwanPP |
	#IETFInterfaces_InterfaceType_wwanPP2 |
	#IETFInterfaces_InterfaceType_x213 |
	#IETFInterfaces_InterfaceType_x25huntGroup |
	#IETFInterfaces_InterfaceType_x25mlp |
	#IETFInterfaces_InterfaceType_x25ple |
	#IETFInterfaces_InterfaceType_x86Laps

#values_E_IETFInterfaces_InterfaceType: {
	IETFInterfaces_InterfaceType_UNSET:                         #IETFInterfaces_InterfaceType_UNSET
	IETFInterfaces_InterfaceType_a12MppSwitch:                  #IETFInterfaces_InterfaceType_a12MppSwitch
	IETFInterfaces_InterfaceType_aal2:                          #IETFInterfaces_InterfaceType_aal2
	IETFInterfaces_InterfaceType_aal5:                          #IETFInterfaces_InterfaceType_aal5
	IETFInterfaces_InterfaceType_actelisMetaLOOP:               #IETFInterfaces_InterfaceType_actelisMetaLOOP
	IETFInterfaces_InterfaceType_adsl:                          #IETFInterfaces_InterfaceType_adsl
	IETFInterfaces_InterfaceType_adsl2:                         #IETFInterfaces_InterfaceType_adsl2
	IETFInterfaces_InterfaceType_adsl2plus:                     #IETFInterfaces_InterfaceType_adsl2plus
	IETFInterfaces_InterfaceType_aflane8023:                    #IETFInterfaces_InterfaceType_aflane8023
	IETFInterfaces_InterfaceType_aflane8025:                    #IETFInterfaces_InterfaceType_aflane8025
	IETFInterfaces_InterfaceType_aluELP:                        #IETFInterfaces_InterfaceType_aluELP
	IETFInterfaces_InterfaceType_aluEpon:                       #IETFInterfaces_InterfaceType_aluEpon
	IETFInterfaces_InterfaceType_aluEponLogicalLink:            #IETFInterfaces_InterfaceType_aluEponLogicalLink
	IETFInterfaces_InterfaceType_aluEponOnu:                    #IETFInterfaces_InterfaceType_aluEponOnu
	IETFInterfaces_InterfaceType_aluEponPhysicalUni:            #IETFInterfaces_InterfaceType_aluEponPhysicalUni
	IETFInterfaces_InterfaceType_aluGponOnu:                    #IETFInterfaces_InterfaceType_aluGponOnu
	IETFInterfaces_InterfaceType_aluGponPhysicalUni:            #IETFInterfaces_InterfaceType_aluGponPhysicalUni
	IETFInterfaces_InterfaceType_arap:                          #IETFInterfaces_InterfaceType_arap
	IETFInterfaces_InterfaceType_arcnet:                        #IETFInterfaces_InterfaceType_arcnet
	IETFInterfaces_InterfaceType_arcnetPlus:                    #IETFInterfaces_InterfaceType_arcnetPlus
	IETFInterfaces_InterfaceType_async:                         #IETFInterfaces_InterfaceType_async
	IETFInterfaces_InterfaceType_atm:                           #IETFInterfaces_InterfaceType_atm
	IETFInterfaces_InterfaceType_atmDxi:                        #IETFInterfaces_InterfaceType_atmDxi
	IETFInterfaces_InterfaceType_atmFuni:                       #IETFInterfaces_InterfaceType_atmFuni
	IETFInterfaces_InterfaceType_atmIma:                        #IETFInterfaces_InterfaceType_atmIma
	IETFInterfaces_InterfaceType_atmLogical:                    #IETFInterfaces_InterfaceType_atmLogical
	IETFInterfaces_InterfaceType_atmRadio:                      #IETFInterfaces_InterfaceType_atmRadio
	IETFInterfaces_InterfaceType_atmSubInterface:               #IETFInterfaces_InterfaceType_atmSubInterface
	IETFInterfaces_InterfaceType_atmVciEndPt:                   #IETFInterfaces_InterfaceType_atmVciEndPt
	IETFInterfaces_InterfaceType_atmVirtual:                    #IETFInterfaces_InterfaceType_atmVirtual
	IETFInterfaces_InterfaceType_atmbond:                       #IETFInterfaces_InterfaceType_atmbond
	IETFInterfaces_InterfaceType_aviciOpticalEther:             #IETFInterfaces_InterfaceType_aviciOpticalEther
	IETFInterfaces_InterfaceType_basicISDN:                     #IETFInterfaces_InterfaceType_basicISDN
	IETFInterfaces_InterfaceType_bgppolicyaccounting:           #IETFInterfaces_InterfaceType_bgppolicyaccounting
	IETFInterfaces_InterfaceType_bits:                          #IETFInterfaces_InterfaceType_bits
	IETFInterfaces_InterfaceType_bridge:                        #IETFInterfaces_InterfaceType_bridge
	IETFInterfaces_InterfaceType_bsc:                           #IETFInterfaces_InterfaceType_bsc
	IETFInterfaces_InterfaceType_cableDownstreamRfPort:         #IETFInterfaces_InterfaceType_cableDownstreamRfPort
	IETFInterfaces_InterfaceType_capwapDot11Bss:                #IETFInterfaces_InterfaceType_capwapDot11Bss
	IETFInterfaces_InterfaceType_capwapDot11Profile:            #IETFInterfaces_InterfaceType_capwapDot11Profile
	IETFInterfaces_InterfaceType_capwapWtpVirtualRadio:         #IETFInterfaces_InterfaceType_capwapWtpVirtualRadio
	IETFInterfaces_InterfaceType_cblVectaStar:                  #IETFInterfaces_InterfaceType_cblVectaStar
	IETFInterfaces_InterfaceType_cctEmul:                       #IETFInterfaces_InterfaceType_cctEmul
	IETFInterfaces_InterfaceType_ces:                           #IETFInterfaces_InterfaceType_ces
	IETFInterfaces_InterfaceType_channel:                       #IETFInterfaces_InterfaceType_channel
	IETFInterfaces_InterfaceType_ciscoISLvlan:                  #IETFInterfaces_InterfaceType_ciscoISLvlan
	IETFInterfaces_InterfaceType_cnr:                           #IETFInterfaces_InterfaceType_cnr
	IETFInterfaces_InterfaceType_coffee:                        #IETFInterfaces_InterfaceType_coffee
	IETFInterfaces_InterfaceType_compositeLink:                 #IETFInterfaces_InterfaceType_compositeLink
	IETFInterfaces_InterfaceType_dcn:                           #IETFInterfaces_InterfaceType_dcn
	IETFInterfaces_InterfaceType_ddnX25:                        #IETFInterfaces_InterfaceType_ddnX25
	IETFInterfaces_InterfaceType_digitalPowerline:              #IETFInterfaces_InterfaceType_digitalPowerline
	IETFInterfaces_InterfaceType_digitalWrapperOverheadChannel: #IETFInterfaces_InterfaceType_digitalWrapperOverheadChannel
	IETFInterfaces_InterfaceType_dlsw:                          #IETFInterfaces_InterfaceType_dlsw
	IETFInterfaces_InterfaceType_docsCableDownstream:           #IETFInterfaces_InterfaceType_docsCableDownstream
	IETFInterfaces_InterfaceType_docsCableMCmtsDownstream:      #IETFInterfaces_InterfaceType_docsCableMCmtsDownstream
	IETFInterfaces_InterfaceType_docsCableMaclayer:             #IETFInterfaces_InterfaceType_docsCableMaclayer
	IETFInterfaces_InterfaceType_docsCableUpstream:             #IETFInterfaces_InterfaceType_docsCableUpstream
	IETFInterfaces_InterfaceType_docsCableUpstreamChannel:      #IETFInterfaces_InterfaceType_docsCableUpstreamChannel
	IETFInterfaces_InterfaceType_docsCableUpstreamRfPort:       #IETFInterfaces_InterfaceType_docsCableUpstreamRfPort
	IETFInterfaces_InterfaceType_ds0:                           #IETFInterfaces_InterfaceType_ds0
	IETFInterfaces_InterfaceType_ds0Bundle:                     #IETFInterfaces_InterfaceType_ds0Bundle
	IETFInterfaces_InterfaceType_ds1:                           #IETFInterfaces_InterfaceType_ds1
	IETFInterfaces_InterfaceType_ds1FDL:                        #IETFInterfaces_InterfaceType_ds1FDL
	IETFInterfaces_InterfaceType_ds3:                           #IETFInterfaces_InterfaceType_ds3
	IETFInterfaces_InterfaceType_dtm:                           #IETFInterfaces_InterfaceType_dtm
	IETFInterfaces_InterfaceType_dvbAsiIn:                      #IETFInterfaces_InterfaceType_dvbAsiIn
	IETFInterfaces_InterfaceType_dvbAsiOut:                     #IETFInterfaces_InterfaceType_dvbAsiOut
	IETFInterfaces_InterfaceType_dvbRccDownstream:              #IETFInterfaces_InterfaceType_dvbRccDownstream
	IETFInterfaces_InterfaceType_dvbRccMacLayer:                #IETFInterfaces_InterfaceType_dvbRccMacLayer
	IETFInterfaces_InterfaceType_dvbRccUpstream:                #IETFInterfaces_InterfaceType_dvbRccUpstream
	IETFInterfaces_InterfaceType_dvbRcsMacLayer:                #IETFInterfaces_InterfaceType_dvbRcsMacLayer
	IETFInterfaces_InterfaceType_dvbRcsTdma:                    #IETFInterfaces_InterfaceType_dvbRcsTdma
	IETFInterfaces_InterfaceType_dvbTdm:                        #IETFInterfaces_InterfaceType_dvbTdm
	IETFInterfaces_InterfaceType_e1:                            #IETFInterfaces_InterfaceType_e1
	IETFInterfaces_InterfaceType_econet:                        #IETFInterfaces_InterfaceType_econet
	IETFInterfaces_InterfaceType_eon:                           #IETFInterfaces_InterfaceType_eon
	IETFInterfaces_InterfaceType_eplrs:                         #IETFInterfaces_InterfaceType_eplrs
	IETFInterfaces_InterfaceType_escon:                         #IETFInterfaces_InterfaceType_escon
	IETFInterfaces_InterfaceType_ethernet3Mbit:                 #IETFInterfaces_InterfaceType_ethernet3Mbit
	IETFInterfaces_InterfaceType_ethernetCsmacd:                #IETFInterfaces_InterfaceType_ethernetCsmacd
	IETFInterfaces_InterfaceType_fast:                          #IETFInterfaces_InterfaceType_fast
	IETFInterfaces_InterfaceType_fastEther:                     #IETFInterfaces_InterfaceType_fastEther
	IETFInterfaces_InterfaceType_fastEtherFX:                   #IETFInterfaces_InterfaceType_fastEtherFX
	IETFInterfaces_InterfaceType_fcipLink:                      #IETFInterfaces_InterfaceType_fcipLink
	IETFInterfaces_InterfaceType_fddi:                          #IETFInterfaces_InterfaceType_fddi
	IETFInterfaces_InterfaceType_fibreChannel:                  #IETFInterfaces_InterfaceType_fibreChannel
	IETFInterfaces_InterfaceType_frDlciEndPt:                   #IETFInterfaces_InterfaceType_frDlciEndPt
	IETFInterfaces_InterfaceType_frForward:                     #IETFInterfaces_InterfaceType_frForward
	IETFInterfaces_InterfaceType_frameRelay:                    #IETFInterfaces_InterfaceType_frameRelay
	IETFInterfaces_InterfaceType_frameRelayInterconnect:        #IETFInterfaces_InterfaceType_frameRelayInterconnect
	IETFInterfaces_InterfaceType_frameRelayMPI:                 #IETFInterfaces_InterfaceType_frameRelayMPI
	IETFInterfaces_InterfaceType_frameRelayService:             #IETFInterfaces_InterfaceType_frameRelayService
	IETFInterfaces_InterfaceType_frf16MfrBundle:                #IETFInterfaces_InterfaceType_frf16MfrBundle
	IETFInterfaces_InterfaceType_g703at2mb:                     #IETFInterfaces_InterfaceType_g703at2mb
	IETFInterfaces_InterfaceType_g703at64k:                     #IETFInterfaces_InterfaceType_g703at64k
	IETFInterfaces_InterfaceType_g9981:                         #IETFInterfaces_InterfaceType_g9981
	IETFInterfaces_InterfaceType_g9982:                         #IETFInterfaces_InterfaceType_g9982
	IETFInterfaces_InterfaceType_g9983:                         #IETFInterfaces_InterfaceType_g9983
	IETFInterfaces_InterfaceType_gfp:                           #IETFInterfaces_InterfaceType_gfp
	IETFInterfaces_InterfaceType_gigabitEthernet:               #IETFInterfaces_InterfaceType_gigabitEthernet
	IETFInterfaces_InterfaceType_gpon:                          #IETFInterfaces_InterfaceType_gpon
	IETFInterfaces_InterfaceType_gr303IDT:                      #IETFInterfaces_InterfaceType_gr303IDT
	IETFInterfaces_InterfaceType_gr303RDT:                      #IETFInterfaces_InterfaceType_gr303RDT
	IETFInterfaces_InterfaceType_gtp:                           #IETFInterfaces_InterfaceType_gtp
	IETFInterfaces_InterfaceType_h323Gatekeeper:                #IETFInterfaces_InterfaceType_h323Gatekeeper
	IETFInterfaces_InterfaceType_h323Proxy:                     #IETFInterfaces_InterfaceType_h323Proxy
	IETFInterfaces_InterfaceType_hdh1822:                       #IETFInterfaces_InterfaceType_hdh1822
	IETFInterfaces_InterfaceType_hdlc:                          #IETFInterfaces_InterfaceType_hdlc
	IETFInterfaces_InterfaceType_hdsl2:                         #IETFInterfaces_InterfaceType_hdsl2
	IETFInterfaces_InterfaceType_hiperlan2:                     #IETFInterfaces_InterfaceType_hiperlan2
	IETFInterfaces_InterfaceType_hippi:                         #IETFInterfaces_InterfaceType_hippi
	IETFInterfaces_InterfaceType_hippiInterface:                #IETFInterfaces_InterfaceType_hippiInterface
	IETFInterfaces_InterfaceType_homepna:                       #IETFInterfaces_InterfaceType_homepna
	IETFInterfaces_InterfaceType_hostPad:                       #IETFInterfaces_InterfaceType_hostPad
	IETFInterfaces_InterfaceType_hssi:                          #IETFInterfaces_InterfaceType_hssi
	IETFInterfaces_InterfaceType_hyperchannel:                  #IETFInterfaces_InterfaceType_hyperchannel
	IETFInterfaces_InterfaceType_iana_interface_type:           #IETFInterfaces_InterfaceType_iana_interface_type
	IETFInterfaces_InterfaceType_ibm370parChan:                 #IETFInterfaces_InterfaceType_ibm370parChan
	IETFInterfaces_InterfaceType_idsl:                          #IETFInterfaces_InterfaceType_idsl
	IETFInterfaces_InterfaceType_ieee1394:                      #IETFInterfaces_InterfaceType_ieee1394
	IETFInterfaces_InterfaceType_ieee80211:                     #IETFInterfaces_InterfaceType_ieee80211
	IETFInterfaces_InterfaceType_ieee80212:                     #IETFInterfaces_InterfaceType_ieee80212
	IETFInterfaces_InterfaceType_ieee802154:                    #IETFInterfaces_InterfaceType_ieee802154
	IETFInterfaces_InterfaceType_ieee80216WMAN:                 #IETFInterfaces_InterfaceType_ieee80216WMAN
	IETFInterfaces_InterfaceType_ieee8023adLag:                 #IETFInterfaces_InterfaceType_ieee8023adLag
	IETFInterfaces_InterfaceType_if_gsn:                        #IETFInterfaces_InterfaceType_if_gsn
	IETFInterfaces_InterfaceType_ifPwType:                      #IETFInterfaces_InterfaceType_ifPwType
	IETFInterfaces_InterfaceType_ifVfiType:                     #IETFInterfaces_InterfaceType_ifVfiType
	IETFInterfaces_InterfaceType_ilan:                          #IETFInterfaces_InterfaceType_ilan
	IETFInterfaces_InterfaceType_imt:                           #IETFInterfaces_InterfaceType_imt
	IETFInterfaces_InterfaceType_infiniband:                    #IETFInterfaces_InterfaceType_infiniband
	IETFInterfaces_InterfaceType_interleave:                    #IETFInterfaces_InterfaceType_interleave
	IETFInterfaces_InterfaceType_ip:                            #IETFInterfaces_InterfaceType_ip
	IETFInterfaces_InterfaceType_ipForward:                     #IETFInterfaces_InterfaceType_ipForward
	IETFInterfaces_InterfaceType_ipOverAtm:                     #IETFInterfaces_InterfaceType_ipOverAtm
	IETFInterfaces_InterfaceType_ipOverCdlc:                    #IETFInterfaces_InterfaceType_ipOverCdlc
	IETFInterfaces_InterfaceType_ipOverClaw:                    #IETFInterfaces_InterfaceType_ipOverClaw
	IETFInterfaces_InterfaceType_ipSwitch:                      #IETFInterfaces_InterfaceType_ipSwitch
	IETFInterfaces_InterfaceType_isdn:                          #IETFInterfaces_InterfaceType_isdn
	IETFInterfaces_InterfaceType_isdns:                         #IETFInterfaces_InterfaceType_isdns
	IETFInterfaces_InterfaceType_isdnu:                         #IETFInterfaces_InterfaceType_isdnu
	IETFInterfaces_InterfaceType_iso88022llc:                   #IETFInterfaces_InterfaceType_iso88022llc
	IETFInterfaces_InterfaceType_iso88023Csmacd:                #IETFInterfaces_InterfaceType_iso88023Csmacd
	IETFInterfaces_InterfaceType_iso88024TokenBus:              #IETFInterfaces_InterfaceType_iso88024TokenBus
	IETFInterfaces_InterfaceType_iso88025CRFPInt:               #IETFInterfaces_InterfaceType_iso88025CRFPInt
	IETFInterfaces_InterfaceType_iso88025Dtr:                   #IETFInterfaces_InterfaceType_iso88025Dtr
	IETFInterfaces_InterfaceType_iso88025Fiber:                 #IETFInterfaces_InterfaceType_iso88025Fiber
	IETFInterfaces_InterfaceType_iso88025TokenRing:             #IETFInterfaces_InterfaceType_iso88025TokenRing
	IETFInterfaces_InterfaceType_iso88026Man:                   #IETFInterfaces_InterfaceType_iso88026Man
	IETFInterfaces_InterfaceType_isup:                          #IETFInterfaces_InterfaceType_isup
	IETFInterfaces_InterfaceType_l2vlan:                        #IETFInterfaces_InterfaceType_l2vlan
	IETFInterfaces_InterfaceType_l3ipvlan:                      #IETFInterfaces_InterfaceType_l3ipvlan
	IETFInterfaces_InterfaceType_l3ipxvlan:                     #IETFInterfaces_InterfaceType_l3ipxvlan
	IETFInterfaces_InterfaceType_lapb:                          #IETFInterfaces_InterfaceType_lapb
	IETFInterfaces_InterfaceType_lapd:                          #IETFInterfaces_InterfaceType_lapd
	IETFInterfaces_InterfaceType_lapf:                          #IETFInterfaces_InterfaceType_lapf
	IETFInterfaces_InterfaceType_linegroup:                     #IETFInterfaces_InterfaceType_linegroup
	IETFInterfaces_InterfaceType_lmp:                           #IETFInterfaces_InterfaceType_lmp
	IETFInterfaces_InterfaceType_localTalk:                     #IETFInterfaces_InterfaceType_localTalk
	IETFInterfaces_InterfaceType_macSecControlledIF:            #IETFInterfaces_InterfaceType_macSecControlledIF
	IETFInterfaces_InterfaceType_macSecUncontrolledIF:          #IETFInterfaces_InterfaceType_macSecUncontrolledIF
	IETFInterfaces_InterfaceType_mediaMailOverIp:               #IETFInterfaces_InterfaceType_mediaMailOverIp
	IETFInterfaces_InterfaceType_mfSigLink:                     #IETFInterfaces_InterfaceType_mfSigLink
	IETFInterfaces_InterfaceType_miox25:                        #IETFInterfaces_InterfaceType_miox25
	IETFInterfaces_InterfaceType_mocaVersion1:                  #IETFInterfaces_InterfaceType_mocaVersion1
	IETFInterfaces_InterfaceType_modem:                         #IETFInterfaces_InterfaceType_modem
	IETFInterfaces_InterfaceType_mpc:                           #IETFInterfaces_InterfaceType_mpc
	IETFInterfaces_InterfaceType_mpegTransport:                 #IETFInterfaces_InterfaceType_mpegTransport
	IETFInterfaces_InterfaceType_mpls:                          #IETFInterfaces_InterfaceType_mpls
	IETFInterfaces_InterfaceType_mplsTunnel:                    #IETFInterfaces_InterfaceType_mplsTunnel
	IETFInterfaces_InterfaceType_msdsl:                         #IETFInterfaces_InterfaceType_msdsl
	IETFInterfaces_InterfaceType_mvl:                           #IETFInterfaces_InterfaceType_mvl
	IETFInterfaces_InterfaceType_myrinet:                       #IETFInterfaces_InterfaceType_myrinet
	IETFInterfaces_InterfaceType_nfas:                          #IETFInterfaces_InterfaceType_nfas
	IETFInterfaces_InterfaceType_nsip:                          #IETFInterfaces_InterfaceType_nsip
	IETFInterfaces_InterfaceType_opticalChannel:                #IETFInterfaces_InterfaceType_opticalChannel
	IETFInterfaces_InterfaceType_opticalChannelGroup:           #IETFInterfaces_InterfaceType_opticalChannelGroup
	IETFInterfaces_InterfaceType_opticalTransport:              #IETFInterfaces_InterfaceType_opticalTransport
	IETFInterfaces_InterfaceType_other:                         #IETFInterfaces_InterfaceType_other
	IETFInterfaces_InterfaceType_otnOdu:                        #IETFInterfaces_InterfaceType_otnOdu
	IETFInterfaces_InterfaceType_otnOtu:                        #IETFInterfaces_InterfaceType_otnOtu
	IETFInterfaces_InterfaceType_para:                          #IETFInterfaces_InterfaceType_para
	IETFInterfaces_InterfaceType_pdnEtherLoop1:                 #IETFInterfaces_InterfaceType_pdnEtherLoop1
	IETFInterfaces_InterfaceType_pdnEtherLoop2:                 #IETFInterfaces_InterfaceType_pdnEtherLoop2
	IETFInterfaces_InterfaceType_pip:                           #IETFInterfaces_InterfaceType_pip
	IETFInterfaces_InterfaceType_plc:                           #IETFInterfaces_InterfaceType_plc
	IETFInterfaces_InterfaceType_pon155:                        #IETFInterfaces_InterfaceType_pon155
	IETFInterfaces_InterfaceType_pon622:                        #IETFInterfaces_InterfaceType_pon622
	IETFInterfaces_InterfaceType_pos:                           #IETFInterfaces_InterfaceType_pos
	IETFInterfaces_InterfaceType_ppp:                           #IETFInterfaces_InterfaceType_ppp
	IETFInterfaces_InterfaceType_pppMultilinkBundle:            #IETFInterfaces_InterfaceType_pppMultilinkBundle
	IETFInterfaces_InterfaceType_primaryISDN:                   #IETFInterfaces_InterfaceType_primaryISDN
	IETFInterfaces_InterfaceType_propAtm:                       #IETFInterfaces_InterfaceType_propAtm
	IETFInterfaces_InterfaceType_propBWAp2Mp:                   #IETFInterfaces_InterfaceType_propBWAp2Mp
	IETFInterfaces_InterfaceType_propCnls:                      #IETFInterfaces_InterfaceType_propCnls
	IETFInterfaces_InterfaceType_propDocsWirelessDownstream:    #IETFInterfaces_InterfaceType_propDocsWirelessDownstream
	IETFInterfaces_InterfaceType_propDocsWirelessMaclayer:      #IETFInterfaces_InterfaceType_propDocsWirelessMaclayer
	IETFInterfaces_InterfaceType_propDocsWirelessUpstream:      #IETFInterfaces_InterfaceType_propDocsWirelessUpstream
	IETFInterfaces_InterfaceType_propMultiplexor:               #IETFInterfaces_InterfaceType_propMultiplexor
	IETFInterfaces_InterfaceType_propPointToPointSerial:        #IETFInterfaces_InterfaceType_propPointToPointSerial
	IETFInterfaces_InterfaceType_propVirtual:                   #IETFInterfaces_InterfaceType_propVirtual
	IETFInterfaces_InterfaceType_propWirelessP2P:               #IETFInterfaces_InterfaceType_propWirelessP2P
	IETFInterfaces_InterfaceType_proteon10Mbit:                 #IETFInterfaces_InterfaceType_proteon10Mbit
	IETFInterfaces_InterfaceType_proteon80Mbit:                 #IETFInterfaces_InterfaceType_proteon80Mbit
	IETFInterfaces_InterfaceType_q2931:                         #IETFInterfaces_InterfaceType_q2931
	IETFInterfaces_InterfaceType_qam:                           #IETFInterfaces_InterfaceType_qam
	IETFInterfaces_InterfaceType_qllc:                          #IETFInterfaces_InterfaceType_qllc
	IETFInterfaces_InterfaceType_radioMAC:                      #IETFInterfaces_InterfaceType_radioMAC
	IETFInterfaces_InterfaceType_radsl:                         #IETFInterfaces_InterfaceType_radsl
	IETFInterfaces_InterfaceType_reachDSL:                      #IETFInterfaces_InterfaceType_reachDSL
	IETFInterfaces_InterfaceType_regular1822:                   #IETFInterfaces_InterfaceType_regular1822
	IETFInterfaces_InterfaceType_rfc1483:                       #IETFInterfaces_InterfaceType_rfc1483
	IETFInterfaces_InterfaceType_rfc877x25:                     #IETFInterfaces_InterfaceType_rfc877x25
	IETFInterfaces_InterfaceType_rpr:                           #IETFInterfaces_InterfaceType_rpr
	IETFInterfaces_InterfaceType_rs232:                         #IETFInterfaces_InterfaceType_rs232
	IETFInterfaces_InterfaceType_rsrb:                          #IETFInterfaces_InterfaceType_rsrb
	IETFInterfaces_InterfaceType_sdlc:                          #IETFInterfaces_InterfaceType_sdlc
	IETFInterfaces_InterfaceType_sdsl:                          #IETFInterfaces_InterfaceType_sdsl
	IETFInterfaces_InterfaceType_shdsl:                         #IETFInterfaces_InterfaceType_shdsl
	IETFInterfaces_InterfaceType_sip:                           #IETFInterfaces_InterfaceType_sip
	IETFInterfaces_InterfaceType_sipSig:                        #IETFInterfaces_InterfaceType_sipSig
	IETFInterfaces_InterfaceType_sipTg:                         #IETFInterfaces_InterfaceType_sipTg
	IETFInterfaces_InterfaceType_sixToFour:                     #IETFInterfaces_InterfaceType_sixToFour
	IETFInterfaces_InterfaceType_slip:                          #IETFInterfaces_InterfaceType_slip
	IETFInterfaces_InterfaceType_smdsDxi:                       #IETFInterfaces_InterfaceType_smdsDxi
	IETFInterfaces_InterfaceType_smdsIcip:                      #IETFInterfaces_InterfaceType_smdsIcip
	IETFInterfaces_InterfaceType_softwareLoopback:              #IETFInterfaces_InterfaceType_softwareLoopback
	IETFInterfaces_InterfaceType_sonet:                         #IETFInterfaces_InterfaceType_sonet
	IETFInterfaces_InterfaceType_sonetOverheadChannel:          #IETFInterfaces_InterfaceType_sonetOverheadChannel
	IETFInterfaces_InterfaceType_sonetPath:                     #IETFInterfaces_InterfaceType_sonetPath
	IETFInterfaces_InterfaceType_sonetVT:                       #IETFInterfaces_InterfaceType_sonetVT
	IETFInterfaces_InterfaceType_srp:                           #IETFInterfaces_InterfaceType_srp
	IETFInterfaces_InterfaceType_ss7SigLink:                    #IETFInterfaces_InterfaceType_ss7SigLink
	IETFInterfaces_InterfaceType_stackToStack:                  #IETFInterfaces_InterfaceType_stackToStack
	IETFInterfaces_InterfaceType_starLan:                       #IETFInterfaces_InterfaceType_starLan
	IETFInterfaces_InterfaceType_tdlc:                          #IETFInterfaces_InterfaceType_tdlc
	IETFInterfaces_InterfaceType_teLink:                        #IETFInterfaces_InterfaceType_teLink
	IETFInterfaces_InterfaceType_termPad:                       #IETFInterfaces_InterfaceType_termPad
	IETFInterfaces_InterfaceType_tr008:                         #IETFInterfaces_InterfaceType_tr008
	IETFInterfaces_InterfaceType_transpHdlc:                    #IETFInterfaces_InterfaceType_transpHdlc
	IETFInterfaces_InterfaceType_tunnel:                        #IETFInterfaces_InterfaceType_tunnel
	IETFInterfaces_InterfaceType_ultra:                         #IETFInterfaces_InterfaceType_ultra
	IETFInterfaces_InterfaceType_usb:                           #IETFInterfaces_InterfaceType_usb
	IETFInterfaces_InterfaceType_v11:                           #IETFInterfaces_InterfaceType_v11
	IETFInterfaces_InterfaceType_v35:                           #IETFInterfaces_InterfaceType_v35
	IETFInterfaces_InterfaceType_v36:                           #IETFInterfaces_InterfaceType_v36
	IETFInterfaces_InterfaceType_v37:                           #IETFInterfaces_InterfaceType_v37
	IETFInterfaces_InterfaceType_vdsl:                          #IETFInterfaces_InterfaceType_vdsl
	IETFInterfaces_InterfaceType_vdsl2:                         #IETFInterfaces_InterfaceType_vdsl2
	IETFInterfaces_InterfaceType_virtualIpAddress:              #IETFInterfaces_InterfaceType_virtualIpAddress
	IETFInterfaces_InterfaceType_virtualTg:                     #IETFInterfaces_InterfaceType_virtualTg
	IETFInterfaces_InterfaceType_vmwareNicTeam:                 #IETFInterfaces_InterfaceType_vmwareNicTeam
	IETFInterfaces_InterfaceType_vmwareVirtualNic:              #IETFInterfaces_InterfaceType_vmwareVirtualNic
	IETFInterfaces_InterfaceType_voiceDID:                      #IETFInterfaces_InterfaceType_voiceDID
	IETFInterfaces_InterfaceType_voiceEBS:                      #IETFInterfaces_InterfaceType_voiceEBS
	IETFInterfaces_InterfaceType_voiceEM:                       #IETFInterfaces_InterfaceType_voiceEM
	IETFInterfaces_InterfaceType_voiceEMFGD:                    #IETFInterfaces_InterfaceType_voiceEMFGD
	IETFInterfaces_InterfaceType_voiceEncap:                    #IETFInterfaces_InterfaceType_voiceEncap
	IETFInterfaces_InterfaceType_voiceFGDEANA:                  #IETFInterfaces_InterfaceType_voiceFGDEANA
	IETFInterfaces_InterfaceType_voiceFGDOS:                    #IETFInterfaces_InterfaceType_voiceFGDOS
	IETFInterfaces_InterfaceType_voiceFXO:                      #IETFInterfaces_InterfaceType_voiceFXO
	IETFInterfaces_InterfaceType_voiceFXS:                      #IETFInterfaces_InterfaceType_voiceFXS
	IETFInterfaces_InterfaceType_voiceOverAtm:                  #IETFInterfaces_InterfaceType_voiceOverAtm
	IETFInterfaces_InterfaceType_voiceOverCable:                #IETFInterfaces_InterfaceType_voiceOverCable
	IETFInterfaces_InterfaceType_voiceOverFrameRelay:           #IETFInterfaces_InterfaceType_voiceOverFrameRelay
	IETFInterfaces_InterfaceType_voiceOverIp:                   #IETFInterfaces_InterfaceType_voiceOverIp
	IETFInterfaces_InterfaceType_wwanPP:                        #IETFInterfaces_InterfaceType_wwanPP
	IETFInterfaces_InterfaceType_wwanPP2:                       #IETFInterfaces_InterfaceType_wwanPP2
	IETFInterfaces_InterfaceType_x213:                          #IETFInterfaces_InterfaceType_x213
	IETFInterfaces_InterfaceType_x25huntGroup:                  #IETFInterfaces_InterfaceType_x25huntGroup
	IETFInterfaces_InterfaceType_x25mlp:                        #IETFInterfaces_InterfaceType_x25mlp
	IETFInterfaces_InterfaceType_x25ple:                        #IETFInterfaces_InterfaceType_x25ple
	IETFInterfaces_InterfaceType_x86Laps:                       #IETFInterfaces_InterfaceType_x86Laps
}

#IETFInterfaces_InterfaceType_UNSET:                         #E_IETFInterfaces_InterfaceType & 0
#IETFInterfaces_InterfaceType_a12MppSwitch:                  #E_IETFInterfaces_InterfaceType & 1
#IETFInterfaces_InterfaceType_aal2:                          #E_IETFInterfaces_InterfaceType & 2
#IETFInterfaces_InterfaceType_aal5:                          #E_IETFInterfaces_InterfaceType & 3
#IETFInterfaces_InterfaceType_actelisMetaLOOP:               #E_IETFInterfaces_InterfaceType & 4
#IETFInterfaces_InterfaceType_adsl:                          #E_IETFInterfaces_InterfaceType & 5
#IETFInterfaces_InterfaceType_adsl2:                         #E_IETFInterfaces_InterfaceType & 6
#IETFInterfaces_InterfaceType_adsl2plus:                     #E_IETFInterfaces_InterfaceType & 7
#IETFInterfaces_InterfaceType_aflane8023:                    #E_IETFInterfaces_InterfaceType & 8
#IETFInterfaces_InterfaceType_aflane8025:                    #E_IETFInterfaces_InterfaceType & 9
#IETFInterfaces_InterfaceType_aluELP:                        #E_IETFInterfaces_InterfaceType & 10
#IETFInterfaces_InterfaceType_aluEpon:                       #E_IETFInterfaces_InterfaceType & 11
#IETFInterfaces_InterfaceType_aluEponLogicalLink:            #E_IETFInterfaces_InterfaceType & 12
#IETFInterfaces_InterfaceType_aluEponOnu:                    #E_IETFInterfaces_InterfaceType & 13
#IETFInterfaces_InterfaceType_aluEponPhysicalUni:            #E_IETFInterfaces_InterfaceType & 14
#IETFInterfaces_InterfaceType_aluGponOnu:                    #E_IETFInterfaces_InterfaceType & 15
#IETFInterfaces_InterfaceType_aluGponPhysicalUni:            #E_IETFInterfaces_InterfaceType & 16
#IETFInterfaces_InterfaceType_arap:                          #E_IETFInterfaces_InterfaceType & 17
#IETFInterfaces_InterfaceType_arcnet:                        #E_IETFInterfaces_InterfaceType & 18
#IETFInterfaces_InterfaceType_arcnetPlus:                    #E_IETFInterfaces_InterfaceType & 19
#IETFInterfaces_InterfaceType_async:                         #E_IETFInterfaces_InterfaceType & 20
#IETFInterfaces_InterfaceType_atm:                           #E_IETFInterfaces_InterfaceType & 21
#IETFInterfaces_InterfaceType_atmDxi:                        #E_IETFInterfaces_InterfaceType & 22
#IETFInterfaces_InterfaceType_atmFuni:                       #E_IETFInterfaces_InterfaceType & 23
#IETFInterfaces_InterfaceType_atmIma:                        #E_IETFInterfaces_InterfaceType & 24
#IETFInterfaces_InterfaceType_atmLogical:                    #E_IETFInterfaces_InterfaceType & 25
#IETFInterfaces_InterfaceType_atmRadio:                      #E_IETFInterfaces_InterfaceType & 26
#IETFInterfaces_InterfaceType_atmSubInterface:               #E_IETFInterfaces_InterfaceType & 27
#IETFInterfaces_InterfaceType_atmVciEndPt:                   #E_IETFInterfaces_InterfaceType & 28
#IETFInterfaces_InterfaceType_atmVirtual:                    #E_IETFInterfaces_InterfaceType & 29
#IETFInterfaces_InterfaceType_atmbond:                       #E_IETFInterfaces_InterfaceType & 30
#IETFInterfaces_InterfaceType_aviciOpticalEther:             #E_IETFInterfaces_InterfaceType & 31
#IETFInterfaces_InterfaceType_basicISDN:                     #E_IETFInterfaces_InterfaceType & 32
#IETFInterfaces_InterfaceType_bgppolicyaccounting:           #E_IETFInterfaces_InterfaceType & 33
#IETFInterfaces_InterfaceType_bits:                          #E_IETFInterfaces_InterfaceType & 34
#IETFInterfaces_InterfaceType_bridge:                        #E_IETFInterfaces_InterfaceType & 35
#IETFInterfaces_InterfaceType_bsc:                           #E_IETFInterfaces_InterfaceType & 36
#IETFInterfaces_InterfaceType_cableDownstreamRfPort:         #E_IETFInterfaces_InterfaceType & 37
#IETFInterfaces_InterfaceType_capwapDot11Bss:                #E_IETFInterfaces_InterfaceType & 38
#IETFInterfaces_InterfaceType_capwapDot11Profile:            #E_IETFInterfaces_InterfaceType & 39
#IETFInterfaces_InterfaceType_capwapWtpVirtualRadio:         #E_IETFInterfaces_InterfaceType & 40
#IETFInterfaces_InterfaceType_cblVectaStar:                  #E_IETFInterfaces_InterfaceType & 41
#IETFInterfaces_InterfaceType_cctEmul:                       #E_IETFInterfaces_InterfaceType & 42
#IETFInterfaces_InterfaceType_ces:                           #E_IETFInterfaces_InterfaceType & 43
#IETFInterfaces_InterfaceType_channel:                       #E_IETFInterfaces_InterfaceType & 44
#IETFInterfaces_InterfaceType_ciscoISLvlan:                  #E_IETFInterfaces_InterfaceType & 45
#IETFInterfaces_InterfaceType_cnr:                           #E_IETFInterfaces_InterfaceType & 46
#IETFInterfaces_InterfaceType_coffee:                        #E_IETFInterfaces_InterfaceType & 47
#IETFInterfaces_InterfaceType_compositeLink:                 #E_IETFInterfaces_InterfaceType & 48
#IETFInterfaces_InterfaceType_dcn:                           #E_IETFInterfaces_InterfaceType & 49
#IETFInterfaces_InterfaceType_ddnX25:                        #E_IETFInterfaces_InterfaceType & 50
#IETFInterfaces_InterfaceType_digitalPowerline:              #E_IETFInterfaces_InterfaceType & 51
#IETFInterfaces_InterfaceType_digitalWrapperOverheadChannel: #E_IETFInterfaces_InterfaceType & 52
#IETFInterfaces_InterfaceType_dlsw:                          #E_IETFInterfaces_InterfaceType & 53
#IETFInterfaces_InterfaceType_docsCableDownstream:           #E_IETFInterfaces_InterfaceType & 54
#IETFInterfaces_InterfaceType_docsCableMCmtsDownstream:      #E_IETFInterfaces_InterfaceType & 55
#IETFInterfaces_InterfaceType_docsCableMaclayer:             #E_IETFInterfaces_InterfaceType & 56
#IETFInterfaces_InterfaceType_docsCableUpstream:             #E_IETFInterfaces_InterfaceType & 57
#IETFInterfaces_InterfaceType_docsCableUpstreamChannel:      #E_IETFInterfaces_InterfaceType & 58
#IETFInterfaces_InterfaceType_docsCableUpstreamRfPort:       #E_IETFInterfaces_InterfaceType & 59
#IETFInterfaces_InterfaceType_ds0:                           #E_IETFInterfaces_InterfaceType & 60
#IETFInterfaces_InterfaceType_ds0Bundle:                     #E_IETFInterfaces_InterfaceType & 61
#IETFInterfaces_InterfaceType_ds1:                           #E_IETFInterfaces_InterfaceType & 62
#IETFInterfaces_InterfaceType_ds1FDL:                        #E_IETFInterfaces_InterfaceType & 63
#IETFInterfaces_InterfaceType_ds3:                           #E_IETFInterfaces_InterfaceType & 64
#IETFInterfaces_InterfaceType_dtm:                           #E_IETFInterfaces_InterfaceType & 65
#IETFInterfaces_InterfaceType_dvbAsiIn:                      #E_IETFInterfaces_InterfaceType & 66
#IETFInterfaces_InterfaceType_dvbAsiOut:                     #E_IETFInterfaces_InterfaceType & 67
#IETFInterfaces_InterfaceType_dvbRccDownstream:              #E_IETFInterfaces_InterfaceType & 68
#IETFInterfaces_InterfaceType_dvbRccMacLayer:                #E_IETFInterfaces_InterfaceType & 69
#IETFInterfaces_InterfaceType_dvbRccUpstream:                #E_IETFInterfaces_InterfaceType & 70
#IETFInterfaces_InterfaceType_dvbRcsMacLayer:                #E_IETFInterfaces_InterfaceType & 71
#IETFInterfaces_InterfaceType_dvbRcsTdma:                    #E_IETFInterfaces_InterfaceType & 72
#IETFInterfaces_InterfaceType_dvbTdm:                        #E_IETFInterfaces_InterfaceType & 73
#IETFInterfaces_InterfaceType_e1:                            #E_IETFInterfaces_InterfaceType & 74
#IETFInterfaces_InterfaceType_econet:                        #E_IETFInterfaces_InterfaceType & 75
#IETFInterfaces_InterfaceType_eon:                           #E_IETFInterfaces_InterfaceType & 76
#IETFInterfaces_InterfaceType_eplrs:                         #E_IETFInterfaces_InterfaceType & 77
#IETFInterfaces_InterfaceType_escon:                         #E_IETFInterfaces_InterfaceType & 78
#IETFInterfaces_InterfaceType_ethernet3Mbit:                 #E_IETFInterfaces_InterfaceType & 79
#IETFInterfaces_InterfaceType_ethernetCsmacd:                #E_IETFInterfaces_InterfaceType & 80
#IETFInterfaces_InterfaceType_fast:                          #E_IETFInterfaces_InterfaceType & 81
#IETFInterfaces_InterfaceType_fastEther:                     #E_IETFInterfaces_InterfaceType & 82
#IETFInterfaces_InterfaceType_fastEtherFX:                   #E_IETFInterfaces_InterfaceType & 83
#IETFInterfaces_InterfaceType_fcipLink:                      #E_IETFInterfaces_InterfaceType & 84
#IETFInterfaces_InterfaceType_fddi:                          #E_IETFInterfaces_InterfaceType & 85
#IETFInterfaces_InterfaceType_fibreChannel:                  #E_IETFInterfaces_InterfaceType & 86
#IETFInterfaces_InterfaceType_frDlciEndPt:                   #E_IETFInterfaces_InterfaceType & 87
#IETFInterfaces_InterfaceType_frForward:                     #E_IETFInterfaces_InterfaceType & 88
#IETFInterfaces_InterfaceType_frameRelay:                    #E_IETFInterfaces_InterfaceType & 89
#IETFInterfaces_InterfaceType_frameRelayInterconnect:        #E_IETFInterfaces_InterfaceType & 90
#IETFInterfaces_InterfaceType_frameRelayMPI:                 #E_IETFInterfaces_InterfaceType & 91
#IETFInterfaces_InterfaceType_frameRelayService:             #E_IETFInterfaces_InterfaceType & 92
#IETFInterfaces_InterfaceType_frf16MfrBundle:                #E_IETFInterfaces_InterfaceType & 93
#IETFInterfaces_InterfaceType_g703at2mb:                     #E_IETFInterfaces_InterfaceType & 94
#IETFInterfaces_InterfaceType_g703at64k:                     #E_IETFInterfaces_InterfaceType & 95
#IETFInterfaces_InterfaceType_g9981:                         #E_IETFInterfaces_InterfaceType & 96
#IETFInterfaces_InterfaceType_g9982:                         #E_IETFInterfaces_InterfaceType & 97
#IETFInterfaces_InterfaceType_g9983:                         #E_IETFInterfaces_InterfaceType & 98
#IETFInterfaces_InterfaceType_gfp:                           #E_IETFInterfaces_InterfaceType & 99
#IETFInterfaces_InterfaceType_gigabitEthernet:               #E_IETFInterfaces_InterfaceType & 100
#IETFInterfaces_InterfaceType_gpon:                          #E_IETFInterfaces_InterfaceType & 101
#IETFInterfaces_InterfaceType_gr303IDT:                      #E_IETFInterfaces_InterfaceType & 102
#IETFInterfaces_InterfaceType_gr303RDT:                      #E_IETFInterfaces_InterfaceType & 103
#IETFInterfaces_InterfaceType_gtp:                           #E_IETFInterfaces_InterfaceType & 104
#IETFInterfaces_InterfaceType_h323Gatekeeper:                #E_IETFInterfaces_InterfaceType & 105
#IETFInterfaces_InterfaceType_h323Proxy:                     #E_IETFInterfaces_InterfaceType & 106
#IETFInterfaces_InterfaceType_hdh1822:                       #E_IETFInterfaces_InterfaceType & 107
#IETFInterfaces_InterfaceType_hdlc:                          #E_IETFInterfaces_InterfaceType & 108
#IETFInterfaces_InterfaceType_hdsl2:                         #E_IETFInterfaces_InterfaceType & 109
#IETFInterfaces_InterfaceType_hiperlan2:                     #E_IETFInterfaces_InterfaceType & 110
#IETFInterfaces_InterfaceType_hippi:                         #E_IETFInterfaces_InterfaceType & 111
#IETFInterfaces_InterfaceType_hippiInterface:                #E_IETFInterfaces_InterfaceType & 112
#IETFInterfaces_InterfaceType_homepna:                       #E_IETFInterfaces_InterfaceType & 113
#IETFInterfaces_InterfaceType_hostPad:                       #E_IETFInterfaces_InterfaceType & 114
#IETFInterfaces_InterfaceType_hssi:                          #E_IETFInterfaces_InterfaceType & 115
#IETFInterfaces_InterfaceType_hyperchannel:                  #E_IETFInterfaces_InterfaceType & 116
#IETFInterfaces_InterfaceType_iana_interface_type:           #E_IETFInterfaces_InterfaceType & 117
#IETFInterfaces_InterfaceType_ibm370parChan:                 #E_IETFInterfaces_InterfaceType & 118
#IETFInterfaces_InterfaceType_idsl:                          #E_IETFInterfaces_InterfaceType & 119
#IETFInterfaces_InterfaceType_ieee1394:                      #E_IETFInterfaces_InterfaceType & 120
#IETFInterfaces_InterfaceType_ieee80211:                     #E_IETFInterfaces_InterfaceType & 121
#IETFInterfaces_InterfaceType_ieee80212:                     #E_IETFInterfaces_InterfaceType & 122
#IETFInterfaces_InterfaceType_ieee802154:                    #E_IETFInterfaces_InterfaceType & 123
#IETFInterfaces_InterfaceType_ieee80216WMAN:                 #E_IETFInterfaces_InterfaceType & 124
#IETFInterfaces_InterfaceType_ieee8023adLag:                 #E_IETFInterfaces_InterfaceType & 125
#IETFInterfaces_InterfaceType_if_gsn:                        #E_IETFInterfaces_InterfaceType & 126
#IETFInterfaces_InterfaceType_ifPwType:                      #E_IETFInterfaces_InterfaceType & 127
#IETFInterfaces_InterfaceType_ifVfiType:                     #E_IETFInterfaces_InterfaceType & 128
#IETFInterfaces_InterfaceType_ilan:                          #E_IETFInterfaces_InterfaceType & 129
#IETFInterfaces_InterfaceType_imt:                           #E_IETFInterfaces_InterfaceType & 130
#IETFInterfaces_InterfaceType_infiniband:                    #E_IETFInterfaces_InterfaceType & 131
#IETFInterfaces_InterfaceType_interleave:                    #E_IETFInterfaces_InterfaceType & 132
#IETFInterfaces_InterfaceType_ip:                            #E_IETFInterfaces_InterfaceType & 133
#IETFInterfaces_InterfaceType_ipForward:                     #E_IETFInterfaces_InterfaceType & 134
#IETFInterfaces_InterfaceType_ipOverAtm:                     #E_IETFInterfaces_InterfaceType & 135
#IETFInterfaces_InterfaceType_ipOverCdlc:                    #E_IETFInterfaces_InterfaceType & 136
#IETFInterfaces_InterfaceType_ipOverClaw:                    #E_IETFInterfaces_InterfaceType & 137
#IETFInterfaces_InterfaceType_ipSwitch:                      #E_IETFInterfaces_InterfaceType & 138
#IETFInterfaces_InterfaceType_isdn:                          #E_IETFInterfaces_InterfaceType & 139
#IETFInterfaces_InterfaceType_isdns:                         #E_IETFInterfaces_InterfaceType & 140
#IETFInterfaces_InterfaceType_isdnu:                         #E_IETFInterfaces_InterfaceType & 141
#IETFInterfaces_InterfaceType_iso88022llc:                   #E_IETFInterfaces_InterfaceType & 142
#IETFInterfaces_InterfaceType_iso88023Csmacd:                #E_IETFInterfaces_InterfaceType & 143
#IETFInterfaces_InterfaceType_iso88024TokenBus:              #E_IETFInterfaces_InterfaceType & 144
#IETFInterfaces_InterfaceType_iso88025CRFPInt:               #E_IETFInterfaces_InterfaceType & 145
#IETFInterfaces_InterfaceType_iso88025Dtr:                   #E_IETFInterfaces_InterfaceType & 146
#IETFInterfaces_InterfaceType_iso88025Fiber:                 #E_IETFInterfaces_InterfaceType & 147
#IETFInterfaces_InterfaceType_iso88025TokenRing:             #E_IETFInterfaces_InterfaceType & 148
#IETFInterfaces_InterfaceType_iso88026Man:                   #E_IETFInterfaces_InterfaceType & 149
#IETFInterfaces_InterfaceType_isup:                          #E_IETFInterfaces_InterfaceType & 150
#IETFInterfaces_InterfaceType_l2vlan:                        #E_IETFInterfaces_InterfaceType & 151
#IETFInterfaces_InterfaceType_l3ipvlan:                      #E_IETFInterfaces_InterfaceType & 152
#IETFInterfaces_InterfaceType_l3ipxvlan:                     #E_IETFInterfaces_InterfaceType & 153
#IETFInterfaces_InterfaceType_lapb:                          #E_IETFInterfaces_InterfaceType & 154
#IETFInterfaces_InterfaceType_lapd:                          #E_IETFInterfaces_InterfaceType & 155
#IETFInterfaces_InterfaceType_lapf:                          #E_IETFInterfaces_InterfaceType & 156
#IETFInterfaces_InterfaceType_linegroup:                     #E_IETFInterfaces_InterfaceType & 157
#IETFInterfaces_InterfaceType_lmp:                           #E_IETFInterfaces_InterfaceType & 158
#IETFInterfaces_InterfaceType_localTalk:                     #E_IETFInterfaces_InterfaceType & 159
#IETFInterfaces_InterfaceType_macSecControlledIF:            #E_IETFInterfaces_InterfaceType & 160
#IETFInterfaces_InterfaceType_macSecUncontrolledIF:          #E_IETFInterfaces_InterfaceType & 161
#IETFInterfaces_InterfaceType_mediaMailOverIp:               #E_IETFInterfaces_InterfaceType & 162
#IETFInterfaces_InterfaceType_mfSigLink:                     #E_IETFInterfaces_InterfaceType & 163
#IETFInterfaces_InterfaceType_miox25:                        #E_IETFInterfaces_InterfaceType & 164
#IETFInterfaces_InterfaceType_mocaVersion1:                  #E_IETFInterfaces_InterfaceType & 165
#IETFInterfaces_InterfaceType_modem:                         #E_IETFInterfaces_InterfaceType & 166
#IETFInterfaces_InterfaceType_mpc:                           #E_IETFInterfaces_InterfaceType & 167
#IETFInterfaces_InterfaceType_mpegTransport:                 #E_IETFInterfaces_InterfaceType & 168
#IETFInterfaces_InterfaceType_mpls:                          #E_IETFInterfaces_InterfaceType & 169
#IETFInterfaces_InterfaceType_mplsTunnel:                    #E_IETFInterfaces_InterfaceType & 170
#IETFInterfaces_InterfaceType_msdsl:                         #E_IETFInterfaces_InterfaceType & 171
#IETFInterfaces_InterfaceType_mvl:                           #E_IETFInterfaces_InterfaceType & 172
#IETFInterfaces_InterfaceType_myrinet:                       #E_IETFInterfaces_InterfaceType & 173
#IETFInterfaces_InterfaceType_nfas:                          #E_IETFInterfaces_InterfaceType & 174
#IETFInterfaces_InterfaceType_nsip:                          #E_IETFInterfaces_InterfaceType & 175
#IETFInterfaces_InterfaceType_opticalChannel:                #E_IETFInterfaces_InterfaceType & 176
#IETFInterfaces_InterfaceType_opticalChannelGroup:           #E_IETFInterfaces_InterfaceType & 177
#IETFInterfaces_InterfaceType_opticalTransport:              #E_IETFInterfaces_InterfaceType & 178
#IETFInterfaces_InterfaceType_other:                         #E_IETFInterfaces_InterfaceType & 179
#IETFInterfaces_InterfaceType_otnOdu:                        #E_IETFInterfaces_InterfaceType & 180
#IETFInterfaces_InterfaceType_otnOtu:                        #E_IETFInterfaces_InterfaceType & 181
#IETFInterfaces_InterfaceType_para:                          #E_IETFInterfaces_InterfaceType & 182
#IETFInterfaces_InterfaceType_pdnEtherLoop1:                 #E_IETFInterfaces_InterfaceType & 183
#IETFInterfaces_InterfaceType_pdnEtherLoop2:                 #E_IETFInterfaces_InterfaceType & 184
#IETFInterfaces_InterfaceType_pip:                           #E_IETFInterfaces_InterfaceType & 185
#IETFInterfaces_InterfaceType_plc:                           #E_IETFInterfaces_InterfaceType & 186
#IETFInterfaces_InterfaceType_pon155:                        #E_IETFInterfaces_InterfaceType & 187
#IETFInterfaces_InterfaceType_pon622:                        #E_IETFInterfaces_InterfaceType & 188
#IETFInterfaces_InterfaceType_pos:                           #E_IETFInterfaces_InterfaceType & 189
#IETFInterfaces_InterfaceType_ppp:                           #E_IETFInterfaces_InterfaceType & 190
#IETFInterfaces_InterfaceType_pppMultilinkBundle:            #E_IETFInterfaces_InterfaceType & 191
#IETFInterfaces_InterfaceType_primaryISDN:                   #E_IETFInterfaces_InterfaceType & 192
#IETFInterfaces_InterfaceType_propAtm:                       #E_IETFInterfaces_InterfaceType & 193
#IETFInterfaces_InterfaceType_propBWAp2Mp:                   #E_IETFInterfaces_InterfaceType & 194
#IETFInterfaces_InterfaceType_propCnls:                      #E_IETFInterfaces_InterfaceType & 195
#IETFInterfaces_InterfaceType_propDocsWirelessDownstream:    #E_IETFInterfaces_InterfaceType & 196
#IETFInterfaces_InterfaceType_propDocsWirelessMaclayer:      #E_IETFInterfaces_InterfaceType & 197
#IETFInterfaces_InterfaceType_propDocsWirelessUpstream:      #E_IETFInterfaces_InterfaceType & 198
#IETFInterfaces_InterfaceType_propMultiplexor:               #E_IETFInterfaces_InterfaceType & 199
#IETFInterfaces_InterfaceType_propPointToPointSerial:        #E_IETFInterfaces_InterfaceType & 200
#IETFInterfaces_InterfaceType_propVirtual:                   #E_IETFInterfaces_InterfaceType & 201
#IETFInterfaces_InterfaceType_propWirelessP2P:               #E_IETFInterfaces_InterfaceType & 202
#IETFInterfaces_InterfaceType_proteon10Mbit:                 #E_IETFInterfaces_InterfaceType & 203
#IETFInterfaces_InterfaceType_proteon80Mbit:                 #E_IETFInterfaces_InterfaceType & 204
#IETFInterfaces_InterfaceType_q2931:                         #E_IETFInterfaces_InterfaceType & 205
#IETFInterfaces_InterfaceType_qam:                           #E_IETFInterfaces_InterfaceType & 206
#IETFInterfaces_InterfaceType_qllc:                          #E_IETFInterfaces_InterfaceType & 207
#IETFInterfaces_InterfaceType_radioMAC:                      #E_IETFInterfaces_InterfaceType & 208
#IETFInterfaces_InterfaceType_radsl:                         #E_IETFInterfaces_InterfaceType & 209
#IETFInterfaces_InterfaceType_reachDSL:                      #E_IETFInterfaces_InterfaceType & 210
#IETFInterfaces_InterfaceType_regular1822:                   #E_IETFInterfaces_InterfaceType & 211
#IETFInterfaces_InterfaceType_rfc1483:                       #E_IETFInterfaces_InterfaceType & 212
#IETFInterfaces_InterfaceType_rfc877x25:                     #E_IETFInterfaces_InterfaceType & 213
#IETFInterfaces_InterfaceType_rpr:                           #E_IETFInterfaces_InterfaceType & 214
#IETFInterfaces_InterfaceType_rs232:                         #E_IETFInterfaces_InterfaceType & 215
#IETFInterfaces_InterfaceType_rsrb:                          #E_IETFInterfaces_InterfaceType & 216
#IETFInterfaces_InterfaceType_sdlc:                          #E_IETFInterfaces_InterfaceType & 217
#IETFInterfaces_InterfaceType_sdsl:                          #E_IETFInterfaces_InterfaceType & 218
#IETFInterfaces_InterfaceType_shdsl:                         #E_IETFInterfaces_InterfaceType & 219
#IETFInterfaces_InterfaceType_sip:                           #E_IETFInterfaces_InterfaceType & 220
#IETFInterfaces_InterfaceType_sipSig:                        #E_IETFInterfaces_InterfaceType & 221
#IETFInterfaces_InterfaceType_sipTg:                         #E_IETFInterfaces_InterfaceType & 222
#IETFInterfaces_InterfaceType_sixToFour:                     #E_IETFInterfaces_InterfaceType & 223
#IETFInterfaces_InterfaceType_slip:                          #E_IETFInterfaces_InterfaceType & 224
#IETFInterfaces_InterfaceType_smdsDxi:                       #E_IETFInterfaces_InterfaceType & 225
#IETFInterfaces_InterfaceType_smdsIcip:                      #E_IETFInterfaces_InterfaceType & 226
#IETFInterfaces_InterfaceType_softwareLoopback:              #E_IETFInterfaces_InterfaceType & 227
#IETFInterfaces_InterfaceType_sonet:                         #E_IETFInterfaces_InterfaceType & 228
#IETFInterfaces_InterfaceType_sonetOverheadChannel:          #E_IETFInterfaces_InterfaceType & 229
#IETFInterfaces_InterfaceType_sonetPath:                     #E_IETFInterfaces_InterfaceType & 230
#IETFInterfaces_InterfaceType_sonetVT:                       #E_IETFInterfaces_InterfaceType & 231
#IETFInterfaces_InterfaceType_srp:                           #E_IETFInterfaces_InterfaceType & 232
#IETFInterfaces_InterfaceType_ss7SigLink:                    #E_IETFInterfaces_InterfaceType & 233
#IETFInterfaces_InterfaceType_stackToStack:                  #E_IETFInterfaces_InterfaceType & 234
#IETFInterfaces_InterfaceType_starLan:                       #E_IETFInterfaces_InterfaceType & 235
#IETFInterfaces_InterfaceType_tdlc:                          #E_IETFInterfaces_InterfaceType & 236
#IETFInterfaces_InterfaceType_teLink:                        #E_IETFInterfaces_InterfaceType & 237
#IETFInterfaces_InterfaceType_termPad:                       #E_IETFInterfaces_InterfaceType & 238
#IETFInterfaces_InterfaceType_tr008:                         #E_IETFInterfaces_InterfaceType & 239
#IETFInterfaces_InterfaceType_transpHdlc:                    #E_IETFInterfaces_InterfaceType & 240
#IETFInterfaces_InterfaceType_tunnel:                        #E_IETFInterfaces_InterfaceType & 241
#IETFInterfaces_InterfaceType_ultra:                         #E_IETFInterfaces_InterfaceType & 242
#IETFInterfaces_InterfaceType_usb:                           #E_IETFInterfaces_InterfaceType & 243
#IETFInterfaces_InterfaceType_v11:                           #E_IETFInterfaces_InterfaceType & 244
#IETFInterfaces_InterfaceType_v35:                           #E_IETFInterfaces_InterfaceType & 245
#IETFInterfaces_InterfaceType_v36:                           #E_IETFInterfaces_InterfaceType & 246
#IETFInterfaces_InterfaceType_v37:                           #E_IETFInterfaces_InterfaceType & 247
#IETFInterfaces_InterfaceType_vdsl:                          #E_IETFInterfaces_InterfaceType & 248
#IETFInterfaces_InterfaceType_vdsl2:                         #E_IETFInterfaces_InterfaceType & 249
#IETFInterfaces_InterfaceType_virtualIpAddress:              #E_IETFInterfaces_InterfaceType & 250
#IETFInterfaces_InterfaceType_virtualTg:                     #E_IETFInterfaces_InterfaceType & 251
#IETFInterfaces_InterfaceType_vmwareNicTeam:                 #E_IETFInterfaces_InterfaceType & 252
#IETFInterfaces_InterfaceType_vmwareVirtualNic:              #E_IETFInterfaces_InterfaceType & 253
#IETFInterfaces_InterfaceType_voiceDID:                      #E_IETFInterfaces_InterfaceType & 254
#IETFInterfaces_InterfaceType_voiceEBS:                      #E_IETFInterfaces_InterfaceType & 255
#IETFInterfaces_InterfaceType_voiceEM:                       #E_IETFInterfaces_InterfaceType & 256
#IETFInterfaces_InterfaceType_voiceEMFGD:                    #E_IETFInterfaces_InterfaceType & 257
#IETFInterfaces_InterfaceType_voiceEncap:                    #E_IETFInterfaces_InterfaceType & 258
#IETFInterfaces_InterfaceType_voiceFGDEANA:                  #E_IETFInterfaces_InterfaceType & 259
#IETFInterfaces_InterfaceType_voiceFGDOS:                    #E_IETFInterfaces_InterfaceType & 260
#IETFInterfaces_InterfaceType_voiceFXO:                      #E_IETFInterfaces_InterfaceType & 261
#IETFInterfaces_InterfaceType_voiceFXS:                      #E_IETFInterfaces_InterfaceType & 262
#IETFInterfaces_InterfaceType_voiceOverAtm:                  #E_IETFInterfaces_InterfaceType & 263
#IETFInterfaces_InterfaceType_voiceOverCable:                #E_IETFInterfaces_InterfaceType & 264
#IETFInterfaces_InterfaceType_voiceOverFrameRelay:           #E_IETFInterfaces_InterfaceType & 265
#IETFInterfaces_InterfaceType_voiceOverIp:                   #E_IETFInterfaces_InterfaceType & 266
#IETFInterfaces_InterfaceType_wwanPP:                        #E_IETFInterfaces_InterfaceType & 267
#IETFInterfaces_InterfaceType_wwanPP2:                       #E_IETFInterfaces_InterfaceType & 268
#IETFInterfaces_InterfaceType_x213:                          #E_IETFInterfaces_InterfaceType & 269
#IETFInterfaces_InterfaceType_x25huntGroup:                  #E_IETFInterfaces_InterfaceType & 270
#IETFInterfaces_InterfaceType_x25mlp:                        #E_IETFInterfaces_InterfaceType & 271
#IETFInterfaces_InterfaceType_x25ple:                        #E_IETFInterfaces_InterfaceType & 272
#IETFInterfaces_InterfaceType_x86Laps:                       #E_IETFInterfaces_InterfaceType & 273

#E_Interface_AdminStatus: int64 // #enumE_Interface_AdminStatus

#enumE_Interface_AdminStatus:
	#Interface_AdminStatus_UNSET |
	#Interface_AdminStatus_UP |
	#Interface_AdminStatus_DOWN |
	#Interface_AdminStatus_TESTING

#values_E_Interface_AdminStatus: {
	Interface_AdminStatus_UNSET:   #Interface_AdminStatus_UNSET
	Interface_AdminStatus_UP:      #Interface_AdminStatus_UP
	Interface_AdminStatus_DOWN:    #Interface_AdminStatus_DOWN
	Interface_AdminStatus_TESTING: #Interface_AdminStatus_TESTING
}

#Interface_AdminStatus_UNSET:   #E_Interface_AdminStatus & 0
#Interface_AdminStatus_UP:      #E_Interface_AdminStatus & 1
#Interface_AdminStatus_DOWN:    #E_Interface_AdminStatus & 2
#Interface_AdminStatus_TESTING: #E_Interface_AdminStatus & 3

#E_Interface_OperStatus: int64 // #enumE_Interface_OperStatus

#enumE_Interface_OperStatus:
	#Interface_OperStatus_UNSET |
	#Interface_OperStatus_UP |
	#Interface_OperStatus_DOWN |
	#Interface_OperStatus_TESTING |
	#Interface_OperStatus_UNKNOWN |
	#Interface_OperStatus_DORMANT |
	#Interface_OperStatus_NOT_PRESENT |
	#Interface_OperStatus_LOWER_LAYER_DOWN

#values_E_Interface_OperStatus: {
	Interface_OperStatus_UNSET:            #Interface_OperStatus_UNSET
	Interface_OperStatus_UP:               #Interface_OperStatus_UP
	Interface_OperStatus_DOWN:             #Interface_OperStatus_DOWN
	Interface_OperStatus_TESTING:          #Interface_OperStatus_TESTING
	Interface_OperStatus_UNKNOWN:          #Interface_OperStatus_UNKNOWN
	Interface_OperStatus_DORMANT:          #Interface_OperStatus_DORMANT
	Interface_OperStatus_NOT_PRESENT:      #Interface_OperStatus_NOT_PRESENT
	Interface_OperStatus_LOWER_LAYER_DOWN: #Interface_OperStatus_LOWER_LAYER_DOWN
}

#Interface_OperStatus_UNSET:            #E_Interface_OperStatus & 0
#Interface_OperStatus_UP:               #E_Interface_OperStatus & 1
#Interface_OperStatus_DOWN:             #E_Interface_OperStatus & 2
#Interface_OperStatus_TESTING:          #E_Interface_OperStatus & 3
#Interface_OperStatus_UNKNOWN:          #E_Interface_OperStatus & 4
#Interface_OperStatus_DORMANT:          #E_Interface_OperStatus & 5
#Interface_OperStatus_NOT_PRESENT:      #E_Interface_OperStatus & 6
#Interface_OperStatus_LOWER_LAYER_DOWN: #E_Interface_OperStatus & 7

#E_Neighbor_NeighborState: int64 // #enumE_Neighbor_NeighborState

#enumE_Neighbor_NeighborState:
	#Neighbor_NeighborState_UNSET |
	#Neighbor_NeighborState_INCOMPLETE |
	#Neighbor_NeighborState_REACHABLE |
	#Neighbor_NeighborState_STALE |
	#Neighbor_NeighborState_DELAY |
	#Neighbor_NeighborState_PROBE

#values_E_Neighbor_NeighborState: {
	Neighbor_NeighborState_UNSET:      #Neighbor_NeighborState_UNSET
	Neighbor_NeighborState_INCOMPLETE: #Neighbor_NeighborState_INCOMPLETE
	Neighbor_NeighborState_REACHABLE:  #Neighbor_NeighborState_REACHABLE
	Neighbor_NeighborState_STALE:      #Neighbor_NeighborState_STALE
	Neighbor_NeighborState_DELAY:      #Neighbor_NeighborState_DELAY
	Neighbor_NeighborState_PROBE:      #Neighbor_NeighborState_PROBE
}

#Neighbor_NeighborState_UNSET:      #E_Neighbor_NeighborState & 0
#Neighbor_NeighborState_INCOMPLETE: #E_Neighbor_NeighborState & 1
#Neighbor_NeighborState_REACHABLE:  #E_Neighbor_NeighborState & 2
#Neighbor_NeighborState_STALE:      #E_Neighbor_NeighborState & 3
#Neighbor_NeighborState_DELAY:      #E_Neighbor_NeighborState & 4
#Neighbor_NeighborState_PROBE:      #E_Neighbor_NeighborState & 5

#E_OpenconfigIfAggregate_AggregationType: int64 // #enumE_OpenconfigIfAggregate_AggregationType

#enumE_OpenconfigIfAggregate_AggregationType:
	#OpenconfigIfAggregate_AggregationType_UNSET |
	#OpenconfigIfAggregate_AggregationType_LACP |
	#OpenconfigIfAggregate_AggregationType_STATIC

#values_E_OpenconfigIfAggregate_AggregationType: {
	OpenconfigIfAggregate_AggregationType_UNSET:  #OpenconfigIfAggregate_AggregationType_UNSET
	OpenconfigIfAggregate_AggregationType_LACP:   #OpenconfigIfAggregate_AggregationType_LACP
	OpenconfigIfAggregate_AggregationType_STATIC: #OpenconfigIfAggregate_AggregationType_STATIC
}

#OpenconfigIfAggregate_AggregationType_UNSET:  #E_OpenconfigIfAggregate_AggregationType & 0
#OpenconfigIfAggregate_AggregationType_LACP:   #E_OpenconfigIfAggregate_AggregationType & 1
#OpenconfigIfAggregate_AggregationType_STATIC: #E_OpenconfigIfAggregate_AggregationType & 2

#E_OpenconfigIfEthernet_ETHERNET_SPEED: int64 // #enumE_OpenconfigIfEthernet_ETHERNET_SPEED

#enumE_OpenconfigIfEthernet_ETHERNET_SPEED:
	#OpenconfigIfEthernet_ETHERNET_SPEED_UNSET |
	#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_100GB |
	#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_100MB |
	#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_10GB |
	#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_10MB |
	#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_1GB |
	#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_25GB |
	#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_40GB |
	#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_50GB |
	#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_UNKNOWN

#values_E_OpenconfigIfEthernet_ETHERNET_SPEED: {
	OpenconfigIfEthernet_ETHERNET_SPEED_UNSET:         #OpenconfigIfEthernet_ETHERNET_SPEED_UNSET
	OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_100GB:   #OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_100GB
	OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_100MB:   #OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_100MB
	OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_10GB:    #OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_10GB
	OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_10MB:    #OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_10MB
	OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_1GB:     #OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_1GB
	OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_25GB:    #OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_25GB
	OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_40GB:    #OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_40GB
	OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_50GB:    #OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_50GB
	OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_UNKNOWN: #OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_UNKNOWN
}

#OpenconfigIfEthernet_ETHERNET_SPEED_UNSET:         #E_OpenconfigIfEthernet_ETHERNET_SPEED & 0
#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_100GB:   #E_OpenconfigIfEthernet_ETHERNET_SPEED & 1
#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_100MB:   #E_OpenconfigIfEthernet_ETHERNET_SPEED & 2
#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_10GB:    #E_OpenconfigIfEthernet_ETHERNET_SPEED & 3
#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_10MB:    #E_OpenconfigIfEthernet_ETHERNET_SPEED & 4
#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_1GB:     #E_OpenconfigIfEthernet_ETHERNET_SPEED & 5
#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_25GB:    #E_OpenconfigIfEthernet_ETHERNET_SPEED & 6
#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_40GB:    #E_OpenconfigIfEthernet_ETHERNET_SPEED & 7
#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_50GB:    #E_OpenconfigIfEthernet_ETHERNET_SPEED & 8
#OpenconfigIfEthernet_ETHERNET_SPEED_SPEED_UNKNOWN: #E_OpenconfigIfEthernet_ETHERNET_SPEED & 9

#E_OpenconfigIfIp_IpAddressOrigin: int64 // #enumE_OpenconfigIfIp_IpAddressOrigin

#enumE_OpenconfigIfIp_IpAddressOrigin:
	#OpenconfigIfIp_IpAddressOrigin_UNSET |
	#OpenconfigIfIp_IpAddressOrigin_OTHER |
	#OpenconfigIfIp_IpAddressOrigin_STATIC |
	#OpenconfigIfIp_IpAddressOrigin_DHCP |
	#OpenconfigIfIp_IpAddressOrigin_LINK_LAYER |
	#OpenconfigIfIp_IpAddressOrigin_RANDOM

#values_E_OpenconfigIfIp_IpAddressOrigin: {
	OpenconfigIfIp_IpAddressOrigin_UNSET:      #OpenconfigIfIp_IpAddressOrigin_UNSET
	OpenconfigIfIp_IpAddressOrigin_OTHER:      #OpenconfigIfIp_IpAddressOrigin_OTHER
	OpenconfigIfIp_IpAddressOrigin_STATIC:     #OpenconfigIfIp_IpAddressOrigin_STATIC
	OpenconfigIfIp_IpAddressOrigin_DHCP:       #OpenconfigIfIp_IpAddressOrigin_DHCP
	OpenconfigIfIp_IpAddressOrigin_LINK_LAYER: #OpenconfigIfIp_IpAddressOrigin_LINK_LAYER
	OpenconfigIfIp_IpAddressOrigin_RANDOM:     #OpenconfigIfIp_IpAddressOrigin_RANDOM
}

#OpenconfigIfIp_IpAddressOrigin_UNSET:      #E_OpenconfigIfIp_IpAddressOrigin & 0
#OpenconfigIfIp_IpAddressOrigin_OTHER:      #E_OpenconfigIfIp_IpAddressOrigin & 1
#OpenconfigIfIp_IpAddressOrigin_STATIC:     #E_OpenconfigIfIp_IpAddressOrigin & 2
#OpenconfigIfIp_IpAddressOrigin_DHCP:       #E_OpenconfigIfIp_IpAddressOrigin & 3
#OpenconfigIfIp_IpAddressOrigin_LINK_LAYER: #E_OpenconfigIfIp_IpAddressOrigin & 4
#OpenconfigIfIp_IpAddressOrigin_RANDOM:     #E_OpenconfigIfIp_IpAddressOrigin & 5

#E_OpenconfigIfIp_NeighborOrigin: int64 // #enumE_OpenconfigIfIp_NeighborOrigin

#enumE_OpenconfigIfIp_NeighborOrigin:
	#OpenconfigIfIp_NeighborOrigin_UNSET |
	#OpenconfigIfIp_NeighborOrigin_OTHER |
	#OpenconfigIfIp_NeighborOrigin_STATIC |
	#OpenconfigIfIp_NeighborOrigin_DYNAMIC

#values_E_OpenconfigIfIp_NeighborOrigin: {
	OpenconfigIfIp_NeighborOrigin_UNSET:   #OpenconfigIfIp_NeighborOrigin_UNSET
	OpenconfigIfIp_NeighborOrigin_OTHER:   #OpenconfigIfIp_NeighborOrigin_OTHER
	OpenconfigIfIp_NeighborOrigin_STATIC:  #OpenconfigIfIp_NeighborOrigin_STATIC
	OpenconfigIfIp_NeighborOrigin_DYNAMIC: #OpenconfigIfIp_NeighborOrigin_DYNAMIC
}

#OpenconfigIfIp_NeighborOrigin_UNSET:   #E_OpenconfigIfIp_NeighborOrigin & 0
#OpenconfigIfIp_NeighborOrigin_OTHER:   #E_OpenconfigIfIp_NeighborOrigin & 1
#OpenconfigIfIp_NeighborOrigin_STATIC:  #E_OpenconfigIfIp_NeighborOrigin & 2
#OpenconfigIfIp_NeighborOrigin_DYNAMIC: #E_OpenconfigIfIp_NeighborOrigin & 3

#E_OpenconfigVlanTypes_TPID_TYPES: int64 // #enumE_OpenconfigVlanTypes_TPID_TYPES

#enumE_OpenconfigVlanTypes_TPID_TYPES:
	#OpenconfigVlanTypes_TPID_TYPES_UNSET |
	#OpenconfigVlanTypes_TPID_TYPES_TPID_0X9200 |
	#OpenconfigVlanTypes_TPID_TYPES_TPID_0x8100 |
	#OpenconfigVlanTypes_TPID_TYPES_TPID_0x8A88 |
	#OpenconfigVlanTypes_TPID_TYPES_TPID_0x9100

#values_E_OpenconfigVlanTypes_TPID_TYPES: {
	OpenconfigVlanTypes_TPID_TYPES_UNSET:       #OpenconfigVlanTypes_TPID_TYPES_UNSET
	OpenconfigVlanTypes_TPID_TYPES_TPID_0X9200: #OpenconfigVlanTypes_TPID_TYPES_TPID_0X9200
	OpenconfigVlanTypes_TPID_TYPES_TPID_0x8100: #OpenconfigVlanTypes_TPID_TYPES_TPID_0x8100
	OpenconfigVlanTypes_TPID_TYPES_TPID_0x8A88: #OpenconfigVlanTypes_TPID_TYPES_TPID_0x8A88
	OpenconfigVlanTypes_TPID_TYPES_TPID_0x9100: #OpenconfigVlanTypes_TPID_TYPES_TPID_0x9100
}

#OpenconfigVlanTypes_TPID_TYPES_UNSET:       #E_OpenconfigVlanTypes_TPID_TYPES & 0
#OpenconfigVlanTypes_TPID_TYPES_TPID_0X9200: #E_OpenconfigVlanTypes_TPID_TYPES & 1
#OpenconfigVlanTypes_TPID_TYPES_TPID_0x8100: #E_OpenconfigVlanTypes_TPID_TYPES & 2
#OpenconfigVlanTypes_TPID_TYPES_TPID_0x8A88: #E_OpenconfigVlanTypes_TPID_TYPES & 3
#OpenconfigVlanTypes_TPID_TYPES_TPID_0x9100: #E_OpenconfigVlanTypes_TPID_TYPES & 4

#E_OpenconfigVlanTypes_VlanModeType: int64 // #enumE_OpenconfigVlanTypes_VlanModeType

#enumE_OpenconfigVlanTypes_VlanModeType:
	#OpenconfigVlanTypes_VlanModeType_UNSET |
	#OpenconfigVlanTypes_VlanModeType_ACCESS |
	#OpenconfigVlanTypes_VlanModeType_TRUNK

#values_E_OpenconfigVlanTypes_VlanModeType: {
	OpenconfigVlanTypes_VlanModeType_UNSET:  #OpenconfigVlanTypes_VlanModeType_UNSET
	OpenconfigVlanTypes_VlanModeType_ACCESS: #OpenconfigVlanTypes_VlanModeType_ACCESS
	OpenconfigVlanTypes_VlanModeType_TRUNK:  #OpenconfigVlanTypes_VlanModeType_TRUNK
}

#OpenconfigVlanTypes_VlanModeType_UNSET:  #E_OpenconfigVlanTypes_VlanModeType & 0
#OpenconfigVlanTypes_VlanModeType_ACCESS: #E_OpenconfigVlanTypes_VlanModeType & 1
#OpenconfigVlanTypes_VlanModeType_TRUNK:  #E_OpenconfigVlanTypes_VlanModeType & 2

#E_Vlan_Status: int64 // #enumE_Vlan_Status

#enumE_Vlan_Status:
	#Vlan_Status_UNSET |
	#Vlan_Status_ACTIVE |
	#Vlan_Status_SUSPENDED

#values_E_Vlan_Status: {
	Vlan_Status_UNSET:     #Vlan_Status_UNSET
	Vlan_Status_ACTIVE:    #Vlan_Status_ACTIVE
	Vlan_Status_SUSPENDED: #Vlan_Status_SUSPENDED
}

#Vlan_Status_UNSET:     #E_Vlan_Status & 0
#Vlan_Status_ACTIVE:    #E_Vlan_Status & 1
#Vlan_Status_SUSPENDED: #E_Vlan_Status & 2
