apiVersion: v1
kind: Service
metadata:
  name: ksot-sb-service
spec:
  type: ClusterIP
  selector:
    app: ksot-sb-deployment
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP