apiVersion: v1
kind: Service
metadata:
  name: ksot-nb-service
spec:
  type: ClusterIP
  selector:
    app: ksot-nb-deployment
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP