# permissions for end users to edit devicerollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devicerollout-editor-role
rules:
- apiGroups:
  - kuesta.hrk091.dev
  resources:
  - devicerollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuesta.hrk091.dev
  resources:
  - devicerollouts/status
  verbs:
  - get
