//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Hiroki Okui.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceConfig) DeepCopyInto(out *DeviceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceConfig.
func (in *DeviceConfig) DeepCopy() *DeviceConfig {
	if in == nil {
		return nil
	}
	out := new(DeviceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DeviceConfigMap) DeepCopyInto(out *DeviceConfigMap) {
	{
		in := &in
		*out = make(DeviceConfigMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceConfigMap.
func (in DeviceConfigMap) DeepCopy() DeviceConfigMap {
	if in == nil {
		return nil
	}
	out := new(DeviceConfigMap)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceRollout) DeepCopyInto(out *DeviceRollout) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceRollout.
func (in *DeviceRollout) DeepCopy() *DeviceRollout {
	if in == nil {
		return nil
	}
	out := new(DeviceRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceRollout) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceRolloutList) DeepCopyInto(out *DeviceRolloutList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeviceRollout, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceRolloutList.
func (in *DeviceRolloutList) DeepCopy() *DeviceRolloutList {
	if in == nil {
		return nil
	}
	out := new(DeviceRolloutList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceRolloutList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceRolloutSpec) DeepCopyInto(out *DeviceRolloutSpec) {
	*out = *in
	if in.DeviceConfigMap != nil {
		in, out := &in.DeviceConfigMap, &out.DeviceConfigMap
		*out = make(DeviceConfigMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceRolloutSpec.
func (in *DeviceRolloutSpec) DeepCopy() *DeviceRolloutSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceRolloutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceRolloutStatus) DeepCopyInto(out *DeviceRolloutStatus) {
	*out = *in
	if in.DeviceStatusMap != nil {
		in, out := &in.DeviceStatusMap, &out.DeviceStatusMap
		*out = make(map[string]DeviceStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PrevDeviceConfigMap != nil {
		in, out := &in.PrevDeviceConfigMap, &out.PrevDeviceConfigMap
		*out = make(DeviceConfigMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DesiredDeviceConfigMap != nil {
		in, out := &in.DesiredDeviceConfigMap, &out.DesiredDeviceConfigMap
		*out = make(DeviceConfigMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceRolloutStatus.
func (in *DeviceRolloutStatus) DeepCopy() *DeviceRolloutStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceRolloutStatus)
	in.DeepCopyInto(out)
	return out
}
