apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default

patches:
- patch.yaml

replacements:
  - source:
      kind: Deployment
      name: device-operator-controller-manager
      fieldPath: spec.template.spec.containers.[name=manager].image
      options:
        delimiter: ":"
        index: 1
    targets:
      - fieldPaths:
          - spec.template.spec.containers.[name=manager].env.[name=KUESTA_SUBSCRIBER_IMAGE_VERSION].value
        select:
          kind: Deployment
          name: device-operator-controller-manager
