apiVersion: v1
kind: Service
metadata:
  name: ksot-github-service
spec:
  type: ClusterIP
  selector:
    app: ksot-github-deployment
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP