apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuesta-aggregator
spec:
  template:
    spec:
      containers:
        - name: kuesta
          env:
            - name: KUESTA_STATUS_REPO_URL
              value: https://github.com/kuesta-example/kuesta-status
            - name: KUESTA_GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kuesta-secrets
                  key: gitToken
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuesta-server
spec:
  template:
    spec:
      containers:
        - name: kuesta
          env:
            - name: KUESTA_CONFIG_REPO_URL
              value: https://github.com/kuesta-example/kuesta-config
            - name: KUESTA_STATUS_REPO_URL
              value: https://github.com/kuesta-example/kuesta-status
            - name: KUESTA_GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kuesta-secrets
                  key: gitToken
