name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.18
      IMAGE_REGISTRY: ghcr.io/nttcom/kuesta
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

# TODO enable following after change to public
#      - name: Initialize CodeQL
#        uses: github/codeql-action/init@v2
#        with:
#          languages: go, javascript

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --snapshot --rm-dist

#      - name: Perform CodeQL Analysis
#        uses: github/codeql-action/analyze@v2