# For spec detail, see https://github.com/golangci/golangci-lint-action.
name: golangci-lint
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - uses: actions/checkout@v3
      - name: golangci-lint-nb-server
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./nb-server
          args: --timeout 3m0s
      - name: golangci-lint-github-server
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./github-server
          args: --timeout 3m0s